### ISSUE TITLE
Colab Demo giving error (missing DC Bikes data URL)

### ISSUE THREAD

**Issue by bhollan** [Kanaries/pygwalker#101]
This line of code gives a 404:

`df = pd.read_csv("https://raw.githubusercontent.com/Kanaries/pygwalker/main/tests/bike_sharing_dc.csv", parse_dates=['date'])`

I can make a PR, but this seems like a preference is good to discuss here.  Keep it in this repo? Where? Fetch from somewhere else? Where?

**Comment by Asm-Def** [comment]
Thank you for the feedback!
here's the new link: https://kanaries-app.s3.ap-northeast-1.amazonaws.com/public-datasets/bike_sharing_dc.csv

**Comment by bhollan** [comment]
Nice!  I just realized the colab code isn't in the repo, so I can't actually make a PR.  But you already fixed it! Awesome!
