### ISSUE TITLE
Try support larger data.

### ISSUE THREAD

**Issue by Kindonia** [Kanaries/pygwalker#107]
I like it, if it can support larger data, it will love it!

**Comment by Asm-Def** [comment]
https://github.com/Kanaries/pygwalker/releases/tag/0.1.8.dev0

Here's a development preview of v0.1.8, which allows loading data dynamically.

We'll continue to investigate ways to support larger data as well.

**Comment by longxiaofei** [comment]
No feedback for too long, so temporarily closing this issue. If there are any problems, it can be reopened.
