### ISSUE TITLE
[BUG] PyGWalker not working with Polars

### ISSUE THREAD

**Issue by rdodev** [Kanaries/pygwalker#112]
Running this code below in jupyter notebook
```
import polars as pl
import pygwalker as pyg

df = pl.read_csv('./data.csv')

df

pyg.walk(df)
```

Results in the following error:
`name 'pl' is not defined`

Environment:
Jupyter notebook: 6.5.4
Python: 3.10.4
Polars: 0.17.12

**Comment by Asm-Def** [comment]
Please try https://github.com/Kanaries/pygwalker/releases/tag/0.1.8.dev0, it'll be released soon
