### ISSUE TITLE
Dynamic functions generated with the IFrame aren't recognized in the browser

### ISSUE THREAD

**Issue by Stephen451** [Kanaries/pygwalker#117]
Noticed this running any version of pygwalker after 0.1.5.0a3.  When running pyg.walk with html output set to True, I see the following error in my browser's console (firefox) 
<img width="476" alt="image" src="https://github.com/Kanaries/pygwalker/assets/121068033/87a2bea5-75c8-4586-ac3d-a62959685a8a">

This is causing the iframe to lock into the (I believe) minimum view height of 300 px 

<img width="1006" alt="image" src="https://github.com/Kanaries/pygwalker/assets/121068033/fb20176e-673b-4c23-a645-5ac76359e16e">

which I haven't been able to expand any other way.  It looks like all the frame resizing code included in 0.1.6 is breaking due to this.

**Comment by Asm-Def** [comment]
Thanks for pointing this out! We'll improve the implementation of this part soon.

**Comment by longxiaofei** [comment]
Thank you for your feedback. 

I tried to reproduce this bug but was not successful. Could you please provide me with the code that caused the bug and the version of Firefox you are using? 

Thank you very much.

**Comment by Stephen451** [comment]
Thanks for trying to reproduce!  I'm on 112.0.2 (64-bit), running on MacOSx.

I've already lost track of the code that was causing this problem and with my current implementation everything seems to working fine (using the streamlit interface for now).  I'll try rebuilding the initial attempt I had with raw html and I'll update this comment with code if I see the error again

**Comment by longxiaofei** [comment]
No feedback for too long, so temporarily closing this issue. If there are any problems, it can be reopened.
