### ISSUE TITLE
Can I put pygwalker into Shiny web application (shiny for python)?

### ISSUE THREAD

**Issue by zpio** [Kanaries/pygwalker#118]
Thank you for developing an awesome program! I would like to ask about the supports for Shiny for Python (https://shiny.posit.co/py/)
Please let me know if it is better to ask the Shiny's developers about it.
Thanks in advances.

**Comment by longxiaofei** [comment]
It's a bit late to reply.    (。・＿・。)ﾉI’m sorry~

you can use `pyg.walk(demo_df, return_html=True)`, render the returned html to any engine that can use html.

example for shiny:

```python
from shiny import App, render, ui
import pygwalker as pyg
import pandas as pd

app_ui = ui.page_fluid(
    ui.panel_title("Pygwalker Demo"),

    ui.layout_sidebar(
      ui.panel_sidebar(),
      ui.panel_main(
        ui.output_ui("html")
      ),
    ),
)


def server(input, output, session):
    demo_df = pd.read_csv("your data file path")

    @output
    @render.ui
    def html():
        pyg_html = pyg.walk(demo_df, return_html=True)
        return ui.HTML(pyg_html)


app = App(app_ui, server)

```

**Comment by zpio** [comment]
Thank you so much.

![pywalker](https://github.com/Kanaries/pygwalker/assets/55930230/a6b5315f-4f0f-4624-b36e-b3245c882ea6)

**Comment by iainwallacebms** [comment]
This is a really great example for using Shiny - I would suggest highlighting in the example documentation - https://docs.kanaries.net/pygwalker/tutorials/use-pygwalker-in-shiny
