### ISSUE TITLE
Can I save the config of the plot? Then, I can plot the same figs again when the DataFrame changes.

### ISSUE THREAD

**Issue by AIforDeviceModeling** [Kanaries/pygwalker#122]
Looking forward to your reply.

**Comment by longxiaofei** [comment]
You can upgrade pygWalker to version v0.1.9.1 and use the export feature to fininsh your requirement.

![image](https://github.com/Kanaries/pygwalker/assets/28337703/329c884b-0e7d-42ac-8884-9e3d872c145a)
