### ISSUE TITLE
Multiple Yaxis ?

### ISSUE THREAD

**Issue by tawabshakeel** [Kanaries/pygwalker#123]
Is there any way to add multiple axis?

**Comment by timepasser69** [comment]
as far as im aware of, there is no way yet. ' been using it for the past 10 days'.

**Comment by ObservedObserver** [comment]
Thoughts update from `graphic-walker`:

Sketch different variables in different scales on the same plot always seems misleading. Facets, or separate views, seem more logical for comparing distribution.

**Comment by ObservedObserver** [comment]
related discussion in kanaries discord channels:

> graphic-walker is a vega-lite based system, but vega-lite now does not support to use layers (which is for multiple axis) and facets, which is separate subplots together.

So we choose use support facets, for its more useful for visual exploration, which is the main usecase of graphic-walker.
But as more users of graphic-walker starts to have those demands, we will try to support users to use layers if they are not using facets, and supports facets while disabling layers in future for the first step.

second step maybe fix those "bugs" for upstream, but I remember that it has been a issues for a long time for vega-lite, which might not be easy to fix without some refactoring work, i guess.
OB12er — Today at 8:55 AM
There are some features required layer implementation too:

+ labels
+ confidence interval
+ annotations

So as more users of graphic-walker/pygwalker are voting for those features, we will start the design work more early.

**Comment by ObservedObserver** [comment]
Updates:
this feature now is supported in [graphic-walker](https://github.com/kanaries/graphic-walker)(js SDK of pygwalker), @longxiaofei will release a new version of pygwalker including this soon.
