### ISSUE TITLE
Cannot load more than 

### ISSUE THREAD

**Issue by ruaultadrien** [Kanaries/pygwalker#125]
When I try to embed pygwalker in `streamlit`, I get the following error: 

```
Dataframe is too large for ipynb files. Only 14862 sample items are printed to the file.
```

Is it a known issue that pygwalker cannot handle large datasets?

Thanks a lot for the work, the project looks super cool 😄 

Best,

Adrien

**Comment by longxiaofei** [comment]
use pygwalker in streamlit, reference
https://docs.kanaries.net/pygwalker/use-pygwalker-with-streamlit.en.
