### ISSUE TITLE
Figure's tooltip showing "NaN" for numerical value

### ISSUE THREAD

**Issue by OSuwaidi** [Kanaries/pygwalker#126]
I am new to `pygwalker`, and I have attempted to generate a 2D barplot for my World Happiness Report data; where my X-axis was "Region" (`category` datatype), and my Y-axis was "Happiness_level" (`float64` datatype). And since I had multiple countries per region, I used the "Aggregation" feature, taking the mean of the Y-axis.

While the figure looks good, the tooltip shows `NaN` on for the Y-axis, even though I have no missing (`null`) values at all in my data frame.

Why is that?

**Comment by longxiaofei** [comment]
fixed in version 0.1.11, thanks for your feedback. ♪(･ω･)ﾉ
