### ISSUE TITLE
绘图完之后是否可以全屏？

### ISSUE THREAD

**Issue by suyin1203** [Kanaries/pygwalker#127]
在jupyter中，绘图完成后，想只显示图片，不显示其他绘图菜单栏。请问有这个功能吗？

**Comment by longxiaofei** [comment]
感谢反馈，下次小版本迭代，会更新这个功能。

**Comment by longxiaofei** [comment]
In pygwalker 0.2, `walker.display_chart` feature can do it, But the chart displayed is a png.

Maybe this is not what you want?
