### ISSUE TITLE
Code export showing "Cancel" as "Cancal"

### ISSUE THREAD

**Issue by abfallboerseMWE** [Kanaries/pygwalker#137]
Just a really small one. When clicking on "export_code" on the visualization tab, the pop-out shows "Cancal" instead of "Cancel" on the bottom right (see picture in attachment).

![grafik](https://github.com/Kanaries/pygwalker/assets/111295916/a6ac062d-c1b0-4acf-9e1e-05faa4a30e98)

**Comment by longxiaofei** [comment]
Thanks for your feedback. ♪(･ω･)ﾉ

**Comment by abfallboerseMWE** [comment]
Thank you for your outstanding work!

**Comment by longxiaofei** [comment]
fixed in version 0.1.11.
