### ISSUE TITLE
Customize the interface

### ISSUE THREAD

**Issue by timepasser69** [Kanaries/pygwalker#149]
How to remove the the login icon? Its the last icon beside 'export_code' Icon.

**Comment by longxiaofei** [comment]
you can execute code, hide login icon.
```
import pygwalker_utils.config as pyg_conf
pyg_conf.set_config( { 'privacy': 'offline' })
```

In later versions, we will provide more explicit configuration items to control the display of icons.

**Comment by timepasser69** [comment]
> Thank you very much. it works like charm.
