### ISSUE TITLE
可以添加支持自定义图表吗

### ISSUE THREAD

**Issue by zhaojun696** [Kanaries/pygwalker#150]

**Comment by longxiaofei** [comment]
for example?

Can you provide some use cases?

**Comment by zhaojun696** [comment]
如果是基于echart，提供一个绘图的js函数，如chart(参数:要绘图的数据，图表区的dom)。

**Comment by zhaojun696** [comment]
这可能不是最优，还需要大佬们优化一下

**Comment by AntoineYANG** [comment]
> 如果是基于echart，提供一个绘图的js函数，如chart(参数:要绘图的数据，图表区的dom)。

"If it's based on echart" I guess, is this a feature request for the support which allow you to replace vega-lite with any other renderers, such as ECharts ?

**Comment by zhaojun696** [comment]
> > 如果是基于echart，提供一个绘图的js函数，如chart(参数:要绘图的数据，图表区的dom)。
> 
> "If it's based on echart" I guess, is this a feature request for the support which allow you to replace vega-lite with any other renderers, such as ECharts ?

# extJs 渲染时额外需要加载的js文件
# extCss 渲染时额外需要加载的css文件
# extChartMenu 扩展菜单列表
# onChange 拖动数据字段后，如果图表名，在extChartMenu中。
# 则触发此js函数，此函数接收3个参数（图表名，要绘图的数据，图表区的dom）

pyg.walk(
    df,extJs=['url',...],extCss=['url',...],
    onChange='''
        function draw(图表名，要绘图的数据，图表区的dom){
            js代码，自行绘制
        }
    '''
)

**Comment by zhaojun696** [comment]
extJs 渲染时额外需要加载的js文件
extCss 渲染时额外需要加载的css文件
extChartMenu 扩展图表菜单
onChange 拖动数据字段后，如果图表名，在extChartMenu中。
则触发此js函数，此函数接收3个参数（图表名，要绘图的数据，图表区的dom）

pyg.walk(
    df,
    extJs=['url',...],
    extCss=['url',...],
    extChartMenu=['热力图','树状图',....]
    onChange='''
        function draw(图表名，要绘图的数据，图表区的dom){
            js代码，自行绘制
        }
    '''
)

> > 如果是基于echart，提供一个绘图的js函数，如chart(参数:要绘图的数据，图表区的dom)。
> 
> "If it's based on echart" I guess, is this a feature request for the support which allow you to replace vega-lite with any other renderers, such as ECharts ?

extJs 渲染时额外需要加载的js文件
extCss 渲染时额外需要加载的css文件
extChartMenu 扩展图表菜单
onChange 拖动数据字段后，如果图表名，在extChartMenu中。
则触发此js函数，此函数接收3个参数（图表名，要绘图的数据，图表区的dom）

pyg.walk(
    df,
    extJs=['url',...],
    extCss=['url',...],
    extChartMenu=['热力图','树状图',....]
    onChange='''
        function draw(图表名，要绘图的数据，图表区的dom){
            js代码，自行绘制
        }
    '''
)

**Comment by zhaojun696** [comment]
> > 如果是基于echart，提供一个绘图的js函数，如chart(参数:要绘图的数据，图表区的dom)。
> 
> "If it's based on echart" I guess, is this a feature request for the support which allow you to replace vega-lite with any other renderers, such as ECharts ?

extJs 渲染时额外需要加载的js文件
extCss 渲染时额外需要加载的css文件
extChartMenu 扩展图表菜单
onChange 拖动数据字段后，如果图表名，在extChartMenu中。
则触发此js函数，此函数接收3个参数（图表名，要绘图的数据，图表区的dom）

pyg.walk(
    df,
    extJs=['url',...],
    extCss=['url',...],
    extChartMenu=['热力图','树状图',....]
    onChange='''
        function draw(图表名，要绘图的数据，图表区的dom){
            js代码，自行绘制
        }
    '''
)

**Comment by ObservedObserver** [comment]
graphic-walker/pygwalker is a graphics system based on grammar of graphics, it will not become a chart system for building dashboard.

It focuses on data exploration and analysis, not low-code tools for charts which is almost useless for data science.
