### ISSUE TITLE
Data view sort randomly

### ISSUE THREAD

**Issue by Erimus-Koo** [Kanaries/pygwalker#160]
- Sort a df, like `df = df.sort_values('colA')`.
- Print(df), get the correct order.
- pyg.walk()
- Press the top left Data, df in the view is random.

In many cases, a prettier df table view is necessary.
e.g. I sorted date, then take the data view, and all date get random order.

**Comment by Erimus-Koo** [comment]
![image](https://github.com/Kanaries/pygwalker/assets/17139670/754d91a6-da02-4d8e-8b11-87949cf01c40)

👆🏻This looks bad (sorted df).

![image](https://github.com/Kanaries/pygwalker/assets/17139670/59b5b815-b798-4945-b1b1-d534dcf7dc8c)

👆🏻Could this be better.

**Comment by longxiaofei** [comment]
So, you want the order in the data view to be the same as the df, right?

**Comment by Erimus-Koo** [comment]
Yes

**Comment by Erimus-Koo** [comment]
Not only visualization in graphs but also in tables. 👍🏻

**Comment by Erimus-Koo** [comment]
There's another sort case in the filter

![image](https://github.com/Kanaries/pygwalker/assets/17139670/19f137ad-85d3-4fb7-ba09-2d7886a70627)

**Comment by longxiaofei** [comment]
you can new filter tool in verson 0.2.2.
