### ISSUE TITLE
Publish to Django gives a blank page - like issue 94 but getting js and css errors

### ISSUE THREAD

**Issue by terryelewis** [Kanaries/pygwalker#179]
My df object is hitting the html page but i get a heap of junk in the runserver terminal and the html page is blank. I am using the following js and css urls and they are giving errors:
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pygwalker@1.0.0/dist/pygwalker.css">
<script src="https://cdn.jsdelivr.net/npm/pygwalker@1.0.0/dist/pygwalker.js"></script>

Also had errors with cdn.pygwalker.com. Chart.js and jquery.js load no problem.

The same df works well in a notebook.

**Comment by longxiaofei** [comment]
Hi, Can you tell me which version of pygwalker you are currently using?

Or can you tell how you installed pygwalker?

kanaries team never released the `pygwalker@1.0.0` npm package, so I need to know some details.

**Comment by terryelewis** [comment]
Hi
PygWalker 0.2.0a3 and Django 4.2.1
pip install in the venv "env"
Package            Version
------------------ -------
annotated-types    0.5.0
asgiref            3.6.0
astor              0.8.1
asttokens          2.2.1
backcall           0.2.0
colorama           0.4.6
comm               0.1.3
debugpy            1.6.7
decorator          5.1.1
Django             4.2.1
django-ckeditor    6.5.1
django-filter      23.2
django-js-asset    2.0.0
executing          1.2.0
importlib          1.0.4
importlib-metadata 6.8.0
ipykernel          6.24.0
ipython            8.14.0
ipywidgets         8.0.7
jedi               0.18.2
Jinja2             3.1.2
jupyter_client     8.3.0
jupyter_core       5.3.1
jupyterlab-widgets 3.0.8
MarkupSafe         2.1.3
matplotlib-inline  0.1.6
mysql              0.0.3
mysql-connector    2.2.9
mysqlclient        2.1.1
nest-asyncio       1.5.6
numpy              1.25.1
packaging          23.1
pandas             2.0.3
parso              0.8.3
pickleshare        0.7.5
pip                23.2
platformdirs       3.9.1
prompt-toolkit     3.0.39
psutil             5.9.5
pure-eval          0.2.2
pydantic           2.0.3
pydantic_core      2.3.0
Pygments           2.15.1
pygwalker          0.2.0a3
python-dateutil    2.8.2
pytz               2023.3
pywin32            306
pyzmq              25.1.0
setuptools         58.1.0
six                1.16.0
sqlparse           0.4.4
stack-data         0.6.2
tornado            6.3.2
traitlets          5.9.0
typing_extensions  4.7.1
tzdata             2023.3
wcwidth            0.2.6
widgetsnbextension 4.0.8
zipp               3.16.2
(env) (base) PS C:.............
________________________________

**Comment by longxiaofei** [comment]
ok，I need to confirm two things.

1. which function do you use to get the html of pygwalker? `html = pyg.walker(df, return_html=True)`?
2. `<script src="https://cdn.jsdelivr.net/npm/pygwalker@1.0.0/dist/pygwalker.js"></script>`  this code, did you manually add it to your front-end code?

**Comment by terryelewis** [comment]
1. <div id="pygwalker-container">
  <script>
    var gwalker = {{ gwalker|safe }};
    var container = document.getElementById('pygwalker-container');
    var pyg = new PygWalker(container, gwalker);
  </script>
</div>
2. Yes, with some assistance from ChatGPT
3. From my view:
4. def cwship_pygw(request):
	#Retrieve all Orders objects from the database
    cwship_queryset = xyz.objects.all()
    # Convert the queryset to a list of dictionaries
    cwship_data = list(cwship_queryset.values())
    # Convert the list of dictionaries to a pandas dataframe
    df = pd.DataFrame(cwship_data)
    # Call pyg.walk() on the dataframe
    gwalker = pyg.walk(df)
    # Render the HTML template with the gwalker object
    return render(request, 'cwship_pygw.html', {'gwalker': gwalker})

**Comment by longxiaofei** [comment]
1. in `django`

```python
.....
df = pd.DataFrame(cwship_data)
pygwalker_html = pyg.walk(df, return_html=True)
return render(request, 'cwship_pygw.html', {'pygwalker_html': pygwalker_html})
.....
```

2. in `cwship_pygw.html`
```html
......
<!--  where you want to render pygwalker -->
{{ pygwalker_html | safe }}
......
```

**Comment by terryelewis** [comment]
Thanks for your assistance. That worked so well.  I was over cooking things.
Cheers


Kind Regards
Terry Lewis
________________________________
