### ISSUE TITLE
Open Source License UNCLEAR for commercial developers ?  

### ISSUE THREAD

**Issue by richlysakowski** [Kanaries/pygwalker#187]
Please clarify the licensing terms for the PyGWalker codebase for corporate or commercial developer.    It looks like you are charging $10 per month for PyGWalker.  

Is PyGWalker completely Free and Open Source?    Please clarify the FOSS terms for PyGWalker.   
Can it be forever decoupled from your other commercial products? 

Please explain your licensing terms for people who want to use or embed PyGWalker codebase:
   1) into their own applications, for internal use with PyGWalker code embedded.  
   2) into their own applications, for possibly resale with PyGWalker code embedded.  

On the PyGWalker home page there is a "Plans" button in the upper right hand corner.  

    https://docs.kanaries.net/pygwalker 

When I click on that it says the minimum plan is "Plus", not FREE: 

- - Plus
- - $10.00 per month 
- - 5-day free trial
- - Kanaries RATH (Augmented Analytics) Plus
- - Dataset Size Up to 200,000 Rows
- - vizGPT: Build Data Visualization with Chat Interface
- - Graphic Walker: Embeddable Visual Analysis
- - PyGWalker: No-code Visual Analysis in Jupyter Notebook
- - Cloud Storage Space Up to 2GB
- 

I don't want to use RATH or vizGPT, because these look like proprietary licensed technologies that use specific AI backends.  

The "Branding and Attribution" terms are not standard for Apache licenses.  The "White Label License" are rather onerous in the PyGWalker "License 2", which was just updated 5 days ago.   The cost for white label licenses is missing on your website?   I want to see transparency about this problem.  

## 2. Branding and Attribution

You are allowed to integrate the Software into Your own software products, provided that:

- You must clearly and prominently declare that Your software product is based on or incorporates the Software, in all user interfaces where such information is normally presented, and in all marketing and promotional materials.
  
- You must not modify, remove, or obscure any branding information, logos, trademarks, or other proprietary notices in the Software, including but not limited to the "Kanaries" logo. You must keep the "Kanaries" logo intact and unmodified, and it must be clearly visible in all user interfaces where it is normally presented, and in all marketing and promotional materials.
  
## 3. White Label License

If You wish to use the Software in a "white label" manner, where Your branding replaces the original branding of the Software, You must apply for and obtain a separate White Label License from Graphic-Walker. Until You obtain such a license, You must comply with the branding and attribution requirements described in Section 2.

Please clarify the FOSS terms for PyGWalker.   Can it be forever decoupled from your other commercial products?

**Comment by ObservedObserver** [comment]
pygwalker is free and open-sourced. I have just removed the pygwalker and graphic-walker from kanaries pricing item, which may have some misleading info. 

I will update more clear terms for white-label licenses. You can use pygwalker(graphic-walker) for free if you do not remove/modify kanaries logo.
