### ISSUE TITLE
PySpark DataFrame Support

### ISSUE THREAD

**Issue by rishabmps** [Kanaries/pygwalker#189]
Native Support for rendering visualizations for PySpark data frame in the Jupyter notebook.
It is OK to introduce some constraints if the sheer size of the data frame makes it difficult to load.

**Comment by longxiaofei** [comment]
Hi, How size(row count, column count, data szie) is your data?

pygwalker will support bigger datas(<= your computer memory size) in future version.

**Comment by rishabmps** [comment]
1M rows, approximately 200 columns (mix of float and categorical values).

**Comment by longxiaofei** [comment]
Pygwalker will support pyspark within the next 4 versions.

**Comment by longxiaofei** [comment]
version 0.3.3 already support `pyspark.dataframe` , but calculation process of spark not suitable to get datas for render charts.

If the dataframe(spark) you end up needing to analyze doesn't exceed three times your machine's RAM, you can convert to `pandas.dataframe`: `df = spark_df.toPandas()`,

then use duckdb to calculation datas in pygwlaker: `pyg.walk(df, use_kernel_calc=True)`

**Comment by rishabh-dream11** [comment]
Pygwalker will support pyspark within the next 4 versions.
@longxiaofei Is this still in plan?

**Comment by longxiaofei** [comment]
@rishabh-dream11 Dataframe of pyspark is currently supported, but pyspark is not suitable for this kind of interactive calculation.
