### ISSUE TITLE
[Feat] Detect white-dark theme and use appropriate theme

### ISSUE THREAD

**Issue by hyiltiz** [Kanaries/pygwalker#20]
Currently, using `pyg.walk(df)` on a Jupyter Notebook with a dark theme renders a white widget, where most text are so low contrast that they are effectively invisible.

**Comment by hyiltiz** [comment]
Does that has any impact on the call site (user API), or it is just an upgrade to the pygwalker's internal calls to graphic-walker?

**Comment by Asm-Def** [comment]
It's just an upgrade of `graphic-walker` itself, but I'd prefer to export an option for user API in the future.

**Comment by ObservedObserver** [comment]
Use pygwalker with auto-theme (based on your device) in the latest version. pip install --upgrade "pygwalker>=0.1.4.6"
