### ISSUE TITLE
pygwalker cannot be updated solely with conda

### ISSUE THREAD

**Issue by xuyan-ru** [Kanaries/pygwalker#204]
Hi there,

I am currently managing a big python environment with python and would like to update pygwalker from 0.1.11 to 0.3.3 using conda.

In order to make most of other packages untouched, I was using `conda update --no-update-deps pygwalker` but it's not updating at all. However, when using `conda update pygwalker` it's working. I know there will be some additional packaged installed for such pygwalker, for example, duckdb, but I think should not be prohibited by --no-update-deps. Can you tell me if I was doing anything wrong or is it something that can be fixed?

Thanks!

**Comment by longxiaofei** [comment]
I try reproduce it, but without success.

my conda version is `23.7.2`.

1. I install `pygwalker=0.1.11`:  `conda install -c conda-forge pygwalker=0.1.11`.
2. I only update pygwalker: `conda update -c conda-forge --no-update-deps pygwalker`

```
## Package Plan ##

  environment location: /Users/douding/anaconda3/envs/test-conda

  added / updated specs:
    - pygwalker


The following packages will be UPDATED:

  pygwalker                             0.1.11-pyhd8ed1ab_0 --> 0.3.3-pyhd8ed1ab_0 


Proceed ([y]/n)?
```

3. I typed `y`, pygwalker updated to `0.3.3`


When you execute `conda update --no-update-deps pygwalker`, what is output?

**Comment by xuyan-ru** [comment]
On my side, it's 

`
Solving environment: done

# All requested packages already installed.
`

Not sure what's going on there, it's still 0.1.11. However, `conda install -c conda-forge pygwalker=0.3.3` can do the update for me, with downgrading one package (pyarrow) from 12.0.0 to 9.0.0.

**Comment by longxiaofei** [comment]
I wrote the wrong command.

what is output of executing `conda update -c conda-forge --no-update-deps pygwalker`?

**Comment by xuyan-ru** [comment]
![screenshot](https://github.com/Kanaries/pygwalker/assets/81831561/7831eb2c-d81e-4aaf-b401-14ef619d48f9)

I think this makes more sense... Wondering if just my conda config is broken at some point?

**Comment by xuyan-ru** [comment]
Thanks! 

btw, the install trick can work only with explicitly defined version number, for example:

`conda install -c conda-forge pygwalker=0.3.3`

hope this helps
