### ISSUE TITLE
I've got 2 warning message

### ISSUE THREAD

**Issue by Erimus-Koo** [Kanaries/pygwalker#210]
![image](https://github.com/Kanaries/pygwalker/assets/17139670/55c0d359-40c3-4385-a4b9-9fbab7af71f0)

## 1st Warning
```
WARNING: parse invoke code failed, This may affect feature of export code.
```
I am unsure about the cause of the first message.

## 2nd Warning
```
WARNING: parse invoke code failed, This may affect feature of export code.
If you are using pygwalker on Jupyter Notebook(version<7) and it can't display properly, please execute code to fix it: `pip install "pygwalker[notebook]" --pre`.(close after 15 seconds)
```
I am using Jupyter-lab 4.0.5, so maybe the mistakes are being recognized as version<7?

I tried installing the `--pre` version, but encountered more errors.

**Comment by longxiaofei** [comment]
## 1st Warning

export code features need to parse your invoke code, this warning mean parse failed, but it didn't effect main features.

## 2nd Warning

This is just a reminder, due to Jupyter's environment is diverse, it's hard to judging what kind of jupyter users are using. If you can use pygwalker normally, ignore this reminder.

BTW, I prefer to invoke pygwalker(>=0.3.0) by: `walker = pyg.walk(df, spec="config.json", use_kernel_calc=True)`

**Comment by Erimus-Koo** [comment]
## 1st Warning
Can I fix the failed **parse**?

## 2nd Warning
My pygwalker is 0.3.4, and the warning is annoying.

I've tried this `walker = pyg.walk(df, spec="config.json", use_kernel_calc=True)`, without `config.json`
I can't feel any change.

Is there some readme or sample of the `config.json`?

**Comment by longxiaofei** [comment]
## 1st Warning

ignore warning

```
import logging

logging.getLogger("pygwalker").setLevel(logging.ERROR)
```

## 2nd Warning

Normally, it closed after 15 seconds.

**Comment by Erimus-Koo** [comment]
## 1st Warning

If I directly use
```
pyg.walk(df, dark='light', use_kernel_calc=True, spec=vis_spec)
```
There's no warning.

But if I use particial function, or
```
def show(df, **kwargs):
    pyg.walk(df, dark='light', use_kernel_calc=True, **kwargs)

show(df, spec=vis_spec)  #use
```
The 1st warning appears.
How did pyg know the kwargs are different?

**Comment by Erimus-Koo** [comment]
And the option `dark` maybe default follow the browser, but in my case
Browser(dark) > Jupyter(light) > pygwalker(default in dark looks not so good)
Is there some attribute of the jupyter theme can be detected.

**Comment by longxiaofei** [comment]
> ## 1st Warning
> If I directly use
> 
> ```
> pyg.walk(df, dark='light', use_kernel_calc=True, spec=vis_spec)
> ```
> 
> There's no warning.
> 
> But if I use particial function, or (in order to change the default settings, instead of setting it every time.)
> 
> ```
> def show(df, **kwargs):
>     pyg.walk(df, dark='light', use_kernel_calc=True, **kwargs)
> 
> show(df, spec=vis_spec)  #use
> ```
> 
> The 1st warning appears. How did pyg know the kwargs are different?

Sorry, I misunderstood your meaning, if you want to fix parse code, code locate: https://github.com/Kanaries/pygwalker/blob/main/pygwalker/services/format_invoke_walk_code.py

Thank you in advance.

**Comment by Erimus-Koo** [comment]
And like matlab options, maybe some like
```
pyg.option('dark', 'light')
pyg.option['dark'] = 'light'
```
can change the global settings.

**Comment by Erimus-Koo** [comment]
> > ## 1st Warning
> > If I directly use
> > ```
> > pyg.walk(df, dark='light', use_kernel_calc=True, spec=vis_spec)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > There's no warning.
> > But if I use particial function, or (in order to change the default settings, instead of setting it every time.)
> > ```
> > def show(df, **kwargs):
> >     pyg.walk(df, dark='light', use_kernel_calc=True, **kwargs)
> > 
> > show(df, spec=vis_spec)  #use
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The 1st warning appears. How did pyg know the kwargs are different?
> 
> Sorry, I misunderstood your meaning, if you want to fix parse code, code locate: https://github.com/Kanaries/pygwalker/blob/main/pygwalker/services/format_invoke_walk_code.py
> 
> Thank you in advance.

I read the code, and I think it should be caused by the `frame` in line 103, but I've no idea about that part.

**Comment by longxiaofei** [comment]
1st warning can ignore by log level temporarily, fix it is not a high priority.

**Comment by Erimus-Koo** [comment]
> 1st warning can ignore by log level temporarily, fix it is not a high priority.
> 
> 
> 
> 

Got it and thank you

**Comment by Erimus-Koo** [comment]
@longxiaofei one more tiny question, Is this output necessary?
<img width="580" alt="image" src="https://github.com/Kanaries/pygwalker/assets/17139670/35ccc44b-39f7-4d29-8e6f-f1217871fae2">

**Comment by longxiaofei** [comment]
@Erimus-Koo 

before, `pyg.walk` only render html.

now, `pyg.walk` render html and return a object, you can use this object to export chart or display chart.

you can try `walker = pyg.walk....`, notebook won't output `<pygwalk... at ....>`.

Maybe I can add empty string `__repr__` method to `PygWalker` class, but I don't think this is a good practice.

```
def __repr__(self) -> str:
    return ""
```

**Comment by Erimus-Koo** [comment]
Well, it does sound very reasonable. 
I'm not quite sure about the output of the notebook, maybe there can be a special `__repr__`. But its priority is not high either.

**Comment by Erimus-Koo** [comment]
I asked ChatGPT, and there's a good solution, add a `;` after the line.

```
show(df, spec=vis_spec);
```

In my case, this works.

**Comment by Erimus-Koo** [comment]
And in another way
```
# wrapped with show, and force the theme to light. (no return)
def show(df, spec='', **kwargs):
    pyg.walk(df, dark='light', spec=spec, **kwargs)


# show returns None, so nothing output
show(df, spec=vis_spec)
```

In the previous version, I used a partial function
```
show = partial(pyg.walk, dark='light')
```

Maybe equal to, the different part is the **return**
```
def show(df, spec='', **kwargs):
    return pyg.walk(df, dark='light', spec=spec, **kwargs)
```

**Comment by longxiaofei** [comment]
yes.

The first `show` function, it return None, notebook didn't render None.

The second `show` function, it return PygWalker class, notebook render for default `__repr__` of class.
