### ISSUE TITLE
My system with Manjaro and Jupyter can´t recongnize pygwalker path installed with pipx 

### ISSUE THREAD

**Issue by redhumus** [Kanaries/pygwalker#211]
Hi, 

I'm trying to deal with my new Manjaro update. Searching in forums It seems that at least Manjaro and Debian had deprecated pip. Now, we have to use pipx, virtualenv or systemwide packet manager. 

I installed pipx to install jupytext extension and after i installed pygwalker module. 

I installed pygwalker using pipx but Jupyter is still saying that the module could not be found.
I also installed jupytext but I get the error message starting jupyter:

      File "/home/user/.local/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 177, in _validate_name
        raise ExtensionModuleNotFound(
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'jupytext' could not be found   (No module named 'jupytext'). Are you sure the extension is installed?
    [I 2023-08-25 07:05:13.645 ServerApp] jupyter_server_fileid | extension was successfully linked.
    [I 2023-08-25 07:05:13.647 ServerApp] jupyter_server_ydoc | extension was successfully linked.
    [I 2023-08-25 07:05:13.649 ServerApp] jupyterlab | extension was successfully linked.
    [I 2023-08-25 07:05:13.651 ServerApp] nbclassic | extension was successfully linked.
    [I 2023-08-25 07:05:13.653 ServerApp] notebook | extension was successfully linked.
    [W 2023-08-25 07:05:13.801 ServerApp] jupytext | error adding extension (enabled: True): The module 'jupytext' could not be found (No module named 'jupytext'). Are you sure the extension is installed?

I also checked the Python path and it already includes the directory where the pygwalker module is installed.

    echo $PYTHONPATH                                                                                                                                          
    :/home/user/.local/pipx/venvs/

I also added it the path in detail: export PYTHONPATH=$PYTHONPATH:/home/user/.local/pipx/venvs/pygwalker      

Added the route to .bashrc and .zshrc config files

I tried restarting JupyterLab but the problem still persists.

Could you help me please?

**Comment by longxiaofei** [comment]
I am using pipx for the first time.

I checked related documents about pipx.

Have you tried injecting dependencies into jupyterlab before?

`pipx inject jupyterlab pygwalker`

**Comment by redhumus** [comment]
Thank you. Maybe I'll need to do it that way. I installed jupyter-lab before this pip depreciation, so, pipx can't recognize my old installation of jupyter, so, pipx says: "Can't inject 'pygwalker' into nonexistent Virtual Environment 'jupyter-lab'. Be sure to install the package first with 'pipx install jupyterlab' before injecting into it"

**Comment by longxiaofei** [comment]
Yes, you need to `pipx install jupyterlab`, and run jupyterlab that installed from pipx.

**Comment by redhumus** [comment]
Thank you. I deinstalled wsystem wide jupyter and reinstalled with pipx. then installed pygwalker and then injected on jupyter. All working fine.

Thanks for your help
