### ISSUE TITLE
为什么我保存的配置文件里没有chart_map这个字段？

### ISSUE THREAD

**Issue by DAAworld** [Kanaries/pygwalker#212]
我是用export_to_code按钮保存的配置文件里，没有chart_map内容，导致使用export_chart_png功能没有办法使用

**Comment by longxiaofei** [comment]
Normally, pygwalker didn't save `chart_map` to json file.

`chart_map` will restore in python process memory when you invoke `pyg.walk(...)`, so it shouldn't affect `export_chart_png ` features. 

Can you provide some bug details?

In new pygwalker, I prefer to invoke pygwalker by `walker = pyg.walk(df, spec="./gw.json")`, and use save button to save current chart state.

If you want to save `chart_map` to your json file, use `pyg.walk(df, spec="./gw.json", store_chart_data=True)`
