### ISSUE TITLE
While Loading data around 2 gb with use_kenel_cal = True, the data is not displayed in streamlit

### ISSUE THREAD

**Issue by JeevankumarDharmalingam** [Kanaries/pygwalker#217]

**Comment by longxiaofei** [comment]
currently, `use_kenel_cal=True` not support in streamlit.

**Comment by JeevankumarDharmalingam** [comment]
Can i take it up , guide me where and which file to start , i will try to create a PR

**Comment by longxiaofei** [comment]
nice! I need to take look at documents about `streamlit` communication, after it, I will sync you the details.

by the way, What do you need to implement with pygwalker on streamlit?

**Comment by JeevankumarDharmalingam** [comment]
Yea I have tried it without using use_kenel_cal=True on jupyter the data loading is very slow , but with  use_kenel_cal=True the data loading i super fast

**Comment by longxiaofei** [comment]
Currently streamlit does not provide a easy communication method. But I think we can finish it by streamlit component and some haker methods.

We need to code new communication in python and frontend.

frontend add streamlit components, pass message to python by:
```
Streamlit.setComponentValue(message);
```

python access message by:
```
comm = StreamlitHackerComm()
msg = PygwlakerOnStreamlit(...)
if msg["rid"] != last_rid:
  comm._on_message(msg)
```

After python processing message, render js code pass response to frontend:
```
class StreamlitHackerComm:
    def _on_message(self, data: Any):
        ...
        component.html("""
            <script>...</script>
        """)
```

Frontend add listener as accept message from python, judge which request this response belongs to by rid.

You can refer to the code of jupyter communication: `./pygwalker/communications/hacker_comm.py` and `./app/src/utils/communication.tsx`.

But I think this feature is very difficult for a new pygwalker developer.

If you are interested in this feature, You can find what a simple way to communicate with streamlit.

**Comment by longxiaofei** [comment]
I did some research recently and found that I can hack streamlit’s tornado server.

This would seem less invasive.

**Comment by JeevankumarDharmalingam** [comment]
Hey that's good to hear, Can you revert back the steps to make it happen
1.Streamlit tornado's server
I can try that if you revert with more detailed information
*Thanks & Regards*
*JeevanKumar Dharmalingam*

**Comment by longxiaofei** [comment]
I'm verifying it, If all goes well, I may make a working pre-release version available quickly.

**Comment by JeevankumarDharmalingam** [comment]
Sure that i wanted to be a part of this project, I can share the workload
happily.
*Thanks & Regards*
*Jeevan Kumar Dharmalingam*

**Comment by JeevankumarDharmalingam** [comment]
Any progress for above

**Comment by longxiaofei** [comment]
Even if tornado is hacked, since streamlit is a long running service, I need to consider state management of pygwalker.

I am working at it.

**Comment by JeevankumarDharmalingam** [comment]
@longxiaofei Can you tell me this one, this use_kernal_calc = True will work with any of web applications ?

**Comment by longxiaofei** [comment]
No, only in jupyter.

If you want to use it in your web server, you can use [graphic-walker](https://github.com/Kanaries/graphic-walker) to build frontend, and write your web api, use [gw-dsl-parser-py](https://github.com/Kanaries/gw-dsl-parser-py) to parse dsl of graphic-walker to sql.  

Referring to the above, you can use graphic-walker more flexibly to build your own applications.

**Comment by longxiaofei** [comment]
demo code: https://github.com/Kanaries/pygwalker-in-streamlit/blob/main/pygwalker_comm_demo.py
online url: https://pygwalker-in-app-dngxb2r82ho2zqct244v7b.streamlit.app/
install pre-release: `pip install --upgrade --pre pygwalker`

I can't tell you how to do it, because I'm still figuring it out.

**Comment by JeevankumarDharmalingam** [comment]
Getting this error @longxiaofei 

Oops!
The chart is too large to render. You can try options above:
1. Set the chart to a fixed size. Set Now
2. Change to SVG renderer. Set Now
3. Close this modal and edit the chart to reduce chart size.

**Comment by ObservedObserver** [comment]
It's a front end error in `graphic-walker`, caused by a large scale of canvas crushed (for example, too many bars lead to large with of canvas).

tip 1  & 2 can solved it easier. tip 3 is not quite clear. it means you can select a subset by adding a filter or limit on the graph to make the size of canvas smaller.

**Comment by JeevankumarDharmalingam** [comment]
So you mean fixed chart size should help right, I need insight, like for computation can we point external duckDB and get the processing done, Thanks much in advance !!!

**Comment by JeevankumarDharmalingam** [comment]
When we deploy this code in streamlit which duckDB is used?
Our local or user's machine?
And Where duckDB files are created in local for computation? 
or the data is sent to your end by any api call ?
Please need above clarification
Thanks in advance

**Comment by longxiaofei** [comment]
The data source of duckdb is the memory of your streamlit process.

duckdb is on the machine where your steamlit server is located.
