### ISSUE TITLE
Embedding directly in html

### ISSUE THREAD

**Issue by DeastinY** [Kanaries/pygwalker#24]
So I would love to use pygwalker in my project which is currently serving the data analytics through a simple flask server. Is there any easy way already available?

**Comment by Asm-Def** [comment]
Sure, see [https://github.com/Kanaries/graphic-walker]() for more help.

**Comment by DeastinY** [comment]
How about adding a flag and returning `html = render_gwalker_html(gid, props)` this? Works in my testing. Should I submit a PR or would this not be a feature you want supported?

**Comment by Asm-Def** [comment]
> How about adding a flag and returning `html = render_gwalker_html(gid, props)` for the `walk`? Works in my testing. Should I submit a PR or would this not be a feature you want supported?

I'd prefer to leave this usage as an independent API (like `pyg.to_html(df)`) since it totally doesn't depend on `IPython.display` and could be popularized to other application scenarios more flexibly.

And obviously  `pyg.walk` could act as a caller of `pyg.to_html` as well.

**Comment by DeastinY** [comment]
Thanks! ❤️
