### ISSUE TITLE
Similar to #210 WARNING: parse invoke code failed, This may affect feature of export code.

### ISSUE THREAD

**Issue by terryelewis** [Kanaries/pygwalker#247]
Hi 
I am getting the above warning during runserver using pygwalker 0.3.7 with Django 4.2.1.(#210 was with notebook)
Can I safely ignore?
Kind Regards
Terry

**Comment by longxiaofei** [comment]
yes, you can ignore it.

```python
import logging

logging.getLogger("pygwalker").setLevel(logging.ERROR)
```

**Comment by terryelewis** [comment]
Thanks a ton!
Cheers
Terry

Kind Regards
Terry Lewis
________________________________
