### ISSUE TITLE
When deploying the streamlit apllication the graph is not visible in browser the api calls are going st_core which is not there in directory

### ISSUE THREAD

**Issue by JeevankumarDharmalingam** [Kanaries/pygwalker#252]

**Comment by longxiaofei** [comment]
I don't understand it.

Can I access this app?

**Comment by JeevankumarDharmalingam** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 245, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 447, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 293, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 447, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

**Comment by JeevankumarDharmalingam** [comment]
When i Dockerize the streamlit app will it cause any issue for pygwalker

**Comment by longxiaofei** [comment]
> Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 245, in _get_or_create_cached_value cached_result = cache.read_result(value_key) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 447, in read_result raise CacheKeyNotFoundError() streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 293, in _handle_cache_miss cached_result = cache.read_result(value_key) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 447, in read_result raise CacheKeyNotFoundError() streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

What are the input parameters of the function being cached?

**Comment by longxiaofei** [comment]
> When i Dockerize the streamlit app will it cause any issue for pygwalker

If you can work successfully locally, you can work successfully in docker too.

**Comment by JeevankumarDharmalingam** [comment]
Hey my baseurl is localhost:8080/visualize, but all the request from pygwalker goes to localhost/_stcore/pygwalker/comm, This concerns me the security, is there a way to edit or update to direct pygwalker to localhost/visualize/_stcore/pygwalker/comm

**Comment by longxiaofei** [comment]
> _handle_cache_miss

This is a bug and I will fix it today.

Thanks for feedback.

**Comment by JeevankumarDharmalingam** [comment]
How can i use it when you fix it

**Comment by JeevankumarDharmalingam** [comment]
Is there a way to fix it in local source code , if i fix the below code will it work 
const initStreamlitCommunication = (gid: string) => {
    // temporary solution in streamlit could
    const domain = window.parent.document.location.host.split(".").slice(-2).join('.');
    let url = "";
    if (domain === "streamlit.app") {
        url = `/~/+/_stcore/_pygwalker/comm/${gid}`
    } else {
        url = `/_stcore/_pygwalker/comm/${gid}`

**Comment by longxiaofei** [comment]
@JeevankumarDharmalingam 

Did you use this parameter `--server.baseUrlPath`?

I'm releasing a new version.

**Comment by JeevankumarDharmalingam** [comment]
Yea similar but in config.toml
# The base path for the URL where Streamlit should be served from.
# Default: ""
baseUrlPath =

**Comment by JeevankumarDharmalingam** [comment]
Still issue persists the request is going to http://localhost:8080/_stcore/_pygwalker/comm/2

**Comment by longxiaofei** [comment]
Did you rerun streamlit after `pip install pygwalker==0.3.8a3`?
