### ISSUE TITLE
Date picker does not work in Streamlit

### ISSUE THREAD

**Issue by ilyanoskov** [Kanaries/pygwalker#256]
I am using Pygwalker with Streamlit and it appears that the date picker does not work both with DuckDB and regular format. Can you please confirm it's working?

**Comment by longxiaofei** [comment]
Which the version of pygwalker are you using?

What is the type of your date field?

If it is a string, What is the format of your date field?

**Comment by ilyanoskov** [comment]
> Which the version of pygwalker are you using?
> 
> 
> 
> What is the type of your date field?
> 
> 
> 
> If it is a string, What is the format of your date field?
> 
> 
> 
> 

I am using the latest 0.3.8a2 version that is available on Conda.

The type is pd.to_datetime 

I also tried passing parse_dates parameter but that did not change anything

**Comment by longxiaofei** [comment]
I'm trying to reproduce it.

date picker is working, but there are some time zone bugs.

What is the status with date picker in your data set?

**Comment by ilyanoskov** [comment]
> I'm trying to reproduce it.
> 
> 
> 
> date picker is working, but there are some time zone bugs.
> 
> 
> 
> What is the status with date picker in your dataset?

I am using the UTC timezone, so no timezone issues, however I have a dataset with mixed dates (not continuous dates) and able to select only one month, while the dataset contains different months

**Comment by ilyanoskov** [comment]
With DuckDB I am not able to select any dates and the date picker shows selector for the year 1970

**Comment by longxiaofei** [comment]
Can you give me some sample data?

```python
df[["your_date_field"]][:1000].to_pickle("example.pkl")
```

It's already 1:00 am here, I will reply to you tomorrow.

**Comment by ObservedObserver** [comment]
It's a bug in graphic-walker which can be reproduced with any dataset with temporal field in graphic walker online [playground](graphic-walker.kanaries.net)

**Comment by ilyanoskov** [comment]
Hi @ObservedObserver @longxiaofei @Asm-Def, it appears that the above issue has been fixed? Can you please cut a release for it on Conda so users can start using the date picker again? Thank you very much in advance

**Comment by longxiaofei** [comment]
@ilyanoskov Hi, I discovered another date picker bug during pre-release testing today.

I will release a new version before Oct. 18  after fixing this bug.

**Comment by longxiaofei** [comment]
@ilyanoskov  0.3.8 version already released in conda, But I'm not sure whether to fix this bug(There are too many bugs about date..), looking forward to your feedback.


I only recently noticed this PR:: https://github.com/conda-forge/pygwalker-feedstock/pull/13. Do you need me to add you to CODEOWNERS?

**Comment by ilyanoskov** [comment]
Hi, I have checked out the 0.3.9 version and it seems like it still has date picker bugs in Streamlit. Now, the date ranges are not possible to be selected at all.

This makes Pygwalker not usable for even simple data analysis tasks :(

**Comment by ilyanoskov** [comment]
Correction, the date picker without DuckDB seems to work, but not with DuckDB

**Comment by longxiaofei** [comment]
What is the version of duckdb?

This is a demo(base pygwalker0.3.9, use duckdb): https://pygwalker-in-app-twitter-explore.streamlit.app/

everything looks fine.
