### ISSUE TITLE
Hide Visual Interface for Data Exploration in production environment

### ISSUE THREAD

**Issue by mehtatejas** [Kanaries/pygwalker#257]
Hi,
  I want to use pygwalker for dashboard creation in streamlit.
  In development mode, I want Visual Interface for Data Exploration and chart creation.
  However, I want to hide same in production environment. I just need chart with data filter. 

  Please guide me.

**Comment by longxiaofei** [comment]
Currently, pygwalker can quickly update new version to support it(only render chart without data filter). 

If you need  chart with data filter, it may take many time.

**Comment by ObservedObserver** [comment]
@mehtatejas  We are going to have a release next week(before Oct. 13) to allow you to use both exploration mode and renderer mode in pygwalker.

Features planned in the release:
+ render mode of the chart.
+ filter component can be used outside the exploration UI.
+ A Pure Table component can share the filter / other computation ability of pygwalker

Would love to have more discussions about those features. We will update all related progress, design, development information and documents here.

**Comment by longxiaofei** [comment]
@mehtatejas We have released version 0.3.8a7, detail: https://github.com/Kanaries/pygwalker/releases.

`pip install pygwalker==0.3.8a7`

You can use renderer mode and pre-filters to finish your app.

Looking forward to your feedback.
