### ISSUE TITLE
Ability to delete tabs

### ISSUE THREAD

**Issue by thomasbs17** [Kanaries/pygwalker#266]
Hello,
Thank you for this amazing project. I would like to be able to delete tabs from the UI, but it does not seem to be possible at the moment (I can rename them, but not delete them). 

Do you know if I am missing something? 
If not, is that a scheduled update? 
If this is not scheduled, I am happy to try to work on integration in a separate branch.

_______________________________________________________________________________________________________________________________________
**Logs**:
No error log available
_______________________________________________________________________________________________________________________________________

**Code to reproduce**:

import pygwalker as pyg

pyg.walk(df)

![image](https://github.com/Kanaries/pygwalker/assets/64446011/e3d801a1-8bfc-4ebf-a1c8-6e94308c7be1)

_______________________________________________________________________________________________________________________________________

**Version**:
pygwalker 0.3.7

_______________________________________________________________________________________________________________________________________
Env: Linux and Windows
Python version: 3.8 and above

**Comment by longxiaofei** [comment]
Thanks for feedback.

We will add this feature in 0.3.8 version, you can experience 0.3.8 in advance: `pip install --upgrade --pre pygwalker`

**Comment by longxiaofei** [comment]
0.3.8 version already released.
