### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by JosephItopa** [Kanaries/pygwalker#27]
I am getting this javascript error whenever I run pygwalker over a dataframe on my local jupyter notebook.

![image](https://user-images.githubusercontent.com/28071719/220619346-7d2fccc4-b5ff-4fac-9cdc-e1f2e4626434.png)

**Comment by ssnkhan** [comment]
Seeing similar issues, wrapping the attempt in a `try/except` yields a little more information:

```
Javascript error adding output!
SyntaxError: JSON.parse: bad control character in string literal at line 1 column 290 of the JSON data
See your browser Javascript console for more details.
```

Console output, in `outputarea.js:744`:

```
SyntaxError: JSON.parse: bad control character in string literal at line 1 column 290 of the JSON data
    <anonymous> main.min.js:1202
    append_javascript outputarea.js:772
    append_mime_type outputarea.js:710
    append_display_data outputarea.js:671
    append_output outputarea.js:345
    handle_output outputarea.js:256
    output codecell.js:399
    _handle_output_message kernel.js:1199
    i jQuery
    _handle_iopub_message kernel.js:1239
    _finish_ws_message kernel.js:1018
    _msg_queue kernel.js:1009
```

The data is being loaded into the data frame correctly. I have also tried to escape the original data file, but continue to get similar errors. Any ideas welcomed!

**Comment by jorisroovers** [comment]
Seems similar to #17

**Comment by Asm-Def** [comment]
It seems to have been fixed in #31 and pre-released in `0.1.4-alpha2`.

Could you please have a try with `pip install "pygwalker>=0.1.4-alpha2"` and leave some feedback?


BTW: Welcome to join our discord <a href="https://discord.gg/Z4ngFWXz2U" rel="nofollow"><img alt="discord invitation link" src="https://dcbadge.vercel.app/api/server/Z4ngFWXz2U?style=flat" style="max-width: 100%;" align="middle"></a>  to keep track of the latest progress.

**Comment by JosephItopa** [comment]
This resolved my problem. Thank you. I prefer slack, please if there is a slack channel then I will like to join.

**Comment by Asm-Def** [comment]
Yes, here's our [Slack Invitation](https://join.slack.com/t/kanaries/shared_invite/zt-1k60sgaxu-aGcuS7CwGeJUccE61iGopg)

**Comment by ssnkhan** [comment]
Working for me too, thank you!
