### ISSUE TITLE
`set_config` for privacy not working?

### ISSUE THREAD

**Issue by EricPostMaster** [Kanaries/pygwalker#283]
**Describe the bug**
When I used `set_config` to change my privacy setting from the default, it shows two `privacy` configs, and only one is changed.

**To Reproduce**
In a Databricks notebook running on DBR 13.3

```python
%pip install pygwalker
import pygwalker as pyg
import pygwalker_utils as pyg_utils
import pygwalker_utils.config as pyg_conf

pyg_conf.get_config()
# Output:
# ({'privacy': 'meta'}, {'privacy': 'meta'})

pyg_conf.set_config( { 'privacy': 'offline' }, save=True)

pyg_conf.get_config()
# Output:
# ({'privacy': 'offline'}, {'privacy': 'meta'})
```

**Expected behavior**
I expect to only see one `privacy` configuration. If I see more than one, I expect them to be the same.

**Versions**
- pygwalker version: 0.3.9
- python version: 3.10
- browser: Chrome 117

**Comment by longxiaofei** [comment]
Thanks for feedback, I will improve it in next version.

**Comment by ObservedObserver** [comment]
Thanks for your feedback, and please be aware that we will update to a new policy in the next version.

The basic proposal is:
[pygwalker privacy policy mode]
**offline**: fully offline, no data is sent or api is requested
**update-only**: only check whether this is a new version of pygwalker to update
**events** (default): share which events about which feature is used in pygwalker, it only contains events data about which feature you arrive for product optimization. No DATA YOU ANALYSIS IS SEND.

We decided to change the policy and the default mode is for the purpose of product optimization. We are going to collect whether a user used a feature (just the event) for us to optimize the onboarding process and UX design.

**Comment by EricPostMaster** [comment]
I think the new privacy policy sounds great. I was a little confused by the previous policy, and this is more clear about my main concern, which is whether data I analyze is sent elsewhere. Thanks for clarifying!

**Comment by longxiaofei** [comment]
@EricPostMaster Hi, pygwalker 0.3.10 already released.

If you need new privacy policy, you need to upgrade pygwalker and reconfigure privacy. refer:  [How to set your privacy configuration?](https://github.com/Kanaries/pygwalker/wiki/How-to-set-your-privacy-configuration%3F)
