### ISSUE TITLE
Cannot import name Field from pydantic

### ISSUE THREAD

**Issue by andrnev** [Kanaries/pygwalker#284]
I face this error message when I import pygwalker package and cannot figure out how to fix it. One user reported on SO the same and it was fixed with an upgrade to 0.3.2 from 0.2.1, however I had 0.3.9. So I also tried to downgrade pygwalker to 0.3.2 to see if that solves it but no.  My pydantic version is 0.18.2. I checked the fields.py file in pydantic and I do see the Class Field being defined there so why does it find difficulty in importing?

**Comment by longxiaofei** [comment]
Hi, @andrnev 

try update pydantic version:

```
pip install pydantic==2.4.2
```
