### ISSUE TITLE
HEX support

### ISSUE THREAD

**Issue by giov-bs** [Kanaries/pygwalker#29]
Hi magic people,
I don't know if it is up to the HEX developers or you, but it would be nice if the library could work on HEX notebooks as well. For now it only prints the following:
  
![Screenshot 2023-02-22 at 16 47 10](https://user-images.githubusercontent.com/108722480/220677455-63e09796-f93c-4250-a0e9-945569df79dc.png)
Thank you very much!

**Comment by Asm-Def** [comment]
Could you please have a try with `!pip install 'pygwalker>=0.1.4a1` and give me some feedback?

It's an alpha pre-release version, so the default `pip install pygwalker` won't match this version.

**Comment by giov-bs** [comment]
Tested: now it works both with `!pip install 'pygwalker>=0.1.4a2'` and `!pip install pygwalker` ✅ 
Thank you very much!

**Comment by shamovsky** [comment]
I'm getting the same but as an HTML object.. version 0.1.6.1 of pygwalker. Is there an extra set up step I might have missed?

**Comment by Asm-Def** [comment]
> I'm getting the same but as an HTML object.. version 0.1.6.1 of pygwalker. Is there an extra setup step I might have missed?

Hello, it seems to be because HEX has a limit of about 10MB for HTML code to display.
You can use a random-sampled data frame as a workaround, and please pay attention to our future performance optimization in #97.
