### ISSUE TITLE
Doc build instruction

### ISSUE THREAD

**Issue by ivaquero** [Kanaries/pygwalker#295]
I'd like to build a dash docset for pygwalker, but I don't see any doc files or any instruction for docs building. Will you provide?

**Comment by longxiaofei** [comment]
@ivaquero Hi, Thank you in advance for your contribution. 

Yes, We have been lacking doc build related ways, , we will provide it in this week.

Do you have any suggestions for doc build?

**Comment by longxiaofei** [comment]
@ObservedObserver , What do you think?

**Comment by ivaquero** [comment]
Thank you for the quick reply. 

For docs building, it's better to put the docs in the `docs` branch of this repo, or in the website repo. And there needs to be a package logo.png (32x32) for building convenience.

More importantly, the documents should be automated by CI, for keeping up with the package updates.

**Comment by ObservedObserver** [comment]
We have a doc website of all kanaries repos at docs.kanaries.net, but it contains all docs/guest posts, which might requires a bit of work on decoupling for pygwalker.
