### ISSUE TITLE
New Environment: Flutter (Dart syntax)

### ISSUE THREAD

**Issue by ForeverAngry** [Kanaries/pygwalker#305]
Hi, it would be awesome if this package could support the Flutter Framework (dart). I would be willing to write it or help contribute to it - if someone could break down the services that the existing client environments use!

**Comment by ObservedObserver** [comment]
pygwalker is a Python wrapper of `graphic-walker`, which is written in JavaScript.

The simplest way might be to figure out how to build a wrapper of `graphic-walker` in Dart instead of rewriting the whole code.
