### ISSUE TITLE
[BUG] "Ask" functionality does not work withing Streamlit

### ISSUE THREAD

**Issue by aiakubovich** [Kanaries/pygwalker#307]
**Describe the bug**
"Ask" functionality does not work withing Streamlit

**To Reproduce**
![image](https://github.com/Kanaries/pygwalker/assets/136030897/7ffe757e-2774-4082-961d-30bcfafdc452)

**Expected behavior**
Should plot histogram 

**Versions**
- pygwalker version: 0.3.11
- python version: 3.11
- browser: Edge

**Additional context**
Relevant code:

```
import pygwalker as pyg
import pandas as pd
import streamlit.components.v1 as components
import streamlit as st

# df = ...

pyg_html = pyg.walk(df, 
                    return_html=True,
                    use_kernel_calc=False, 
                    )
 
components.html(pyg_html, height=1000, scrolling=True)
```

**Comment by ObservedObserver** [comment]
1. Have you set a kanaries api key? Cloud services requires a kanaries account and api key. You can following the docs here:
+ https://github.com/Kanaries/pygwalker/wiki/How-to-get-api-key-of-kanaries%3F
+ https://github.com/Kanaries/pygwalker/wiki/How-to-set-your-kanaries-token-in-pygwalker%3F

2. Besides, although it might be able to generate a random chart for you, but I still suggested you put a more related question to the data after you enable the key.

**Comment by aiakubovich** [comment]
Thank you for clarification.

**Comment by longxiaofei** [comment]
Hi, @aiakubovich, thanks for feedback.

`ask-viz` is currently an experimental function, and some error tips  may not be good enough.

In streamlit, If your streamlit app published in public network, your token will be leaked.

We will be fixing these issues in next version(before this week ends).

Also, you can try the new api of pygwalker in streamlit.

[Use new api of pygwalker in streamlit](https://github.com/Kanaries/pygwalker/wiki/About-PyGWalker-0.3.8)
