### ISSUE TITLE
[BUG] pygwalker bug report

### ISSUE THREAD

**Issue by dev72** [Kanaries/pygwalker#310]
**Describe the bug**
in config>format you can set a formatting string for numbers but it is used only for charts, not for tables.

**To Reproduce**
Simply set a formatting string, for example '.2f' then set mak type to table: nothing seems formatted.

**Expected behavior**
Numbers formatted in table same as in charts

**Versions**
- pygwalker version: 0.3.11
- python version: 3.11
- browser

**Comment by BassCoder2808** [comment]
Hi @longxiaofei I would like to work on this issue if it is still open

**Comment by longxiaofei** [comment]
Hi @BassCoder2808 ,  this issue is still open, the developers of graphic-walker will sync the details with you.  @islxyqwe

**Comment by islxyqwe** [comment]
@BassCoder2808 
You can create a pull request at https://github.com/Kanaries/graphic-walker
just get the formatting from `layout.format` and apply it when rendering data in pivot table.
> packages/graphic-walker/src/components/pivotTable/index.tsx
> packages/graphic-walker/src/components/pivotTable/metricTable.tsx
