### ISSUE TITLE
[BUG] pygwalker bug report

### ISSUE THREAD

**Issue by crisfabbri** [Kanaries/pygwalker#319]
**Error saving tables on Streamlit**

**To Reproduce**
Create a table chart, than try to save the chart. An error is returned:
*Error*
*+1 validation error for ChartData singleChart Field required [type=missing, input_value={'mode': 'data-url', 'tit...nRows': 0, 'charts': []},input_type=dict] For further information visit https://errors.pydantic.dev/2.1/v/missing *

**Versions**
- pygwalker version: v0.3.14
- python version: 3.9.16
- Streamlit: 1.28.0

**Additional context**
Same issue with version:
- pygwalker version: v0.3.10
- Streamlit: 1.27.0

**Comment by longxiaofei** [comment]
@crisfabbri  Thanks for feedback. Can you give me your example code to invoke pygwalker?  I will try to reproduce it.

**Comment by longxiaofei** [comment]
I reproduced it.

**Comment by longxiaofei** [comment]
Hi, I fixed this bug, you can use `pip install pygwalker==0.3.15`.

Table chart is different from other charts, It is not a vega chart, so there may be some strange problems when using table chart. I will feedback these issues to the developers of graphic-walker.

Thanks again for your feedback.
