### ISSUE TITLE
[DEV-501] Option to focus to Data tab 

### ISSUE THREAD

**Issue by thienphuoc86** [Kanaries/pygwalker#342]
I would like to request the feature Pygwalk has a option to focus to Data tab when it display.

<sub>[DEV-501](https://linear.app/kanaries/issue/DEV-501/option-to-focus-to-data-tab)</sub>

**Comment by thienphuoc86** [comment]
Hi, Thanks develop team for this feature.
I tested and the pygwalker can focus to data tab now but there is problem when display the datatable.
I use pygwalker with streamlit and my code is below
```
            pyg_html = pyg.to_html(df, default_tab="data")
            components.html(pyg_html, height=1000, scrolling=True)
```
The datatable display as screenshot, you can see the format of first-row of the datatable is not same with the remain rows.
![image](https://github.com/Kanaries/pygwalker/assets/86188301/d71eb5a0-cd51-4199-a310-0ac2350982c6)

**Comment by ObservedObserver** [comment]
Hi, @thienphuoc86 

This is a new feature in pygwalker, it is a column value distribution preview.  The "first row" shows the dirtribution, like top appearance values of the column.

![image](https://github.com/Kanaries/pygwalker/assets/22167673/74a05488-d4b7-4390-9a82-ed775cc937b2)

**Comment by thienphuoc86** [comment]
Hi Elwynn Chen,
Ohh, this feature is interesting, I like it.
But is there any option to hide it?
