### ISSUE TITLE
[DEV-500] [BUG] pygwalker not showing data

### ISSUE THREAD

**Issue by goffk456** [Kanaries/pygwalker#345]
**Describe the bug**
Whenever I run pygwalker in Jupyter notebooks it will originally show the data but when I attempt to visualize it the data disappears past the column names and cannot be visualized

**To Reproduce**

1. Run pygwalker in Jupyter notebook
2. See data present
3. Attempt to visualize data
4. Data besides column names is gone and cannot be visualized

**Expected behavior**
I would expect it to maintain the data and allow me to visualize it

**Screenshots**

![Screenshot 2023-12-06 at 12 46 10 PM](https://uploads.linear.app/f81e7bd9-c8ca-4dfb-b242-4b047e948d40/ed18da33-9466-434d-9ba4-135f63680704/ecb98c8a-56a9-402f-b9f7-e80401595944?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y4MWU3YmQ5LWM4Y2EtNGRmYi1iMjQyLTRiMDQ3ZTk0OGQ0MC9lZDE4ZGEzMy05NDY2LTQzNGQtOWJhNC0xMzVmNjM2ODA3MDQvZWNiOThjOGEtNTZhOS00MDJmLWI5ZjctZTgwNDAxNTk1OTQ0IiwiaWF0IjoxNzAxOTgzMTkwLCJleHAiOjE3MDIwNjk1OTB9.bX6s2L-YHW_HUAHIuWvhWYJXfS0lOi0tn_NnQZdOsmI)

**Versions**

* pygwalker version: 0.3.16
* python version: 3
* browser: Safari

**Additional context**

<sub>From [SyncLinear.com](https://synclinear.com) | [DEV-500](https://linear.app/kanaries/issue/DEV-500/[bug]-pygwalker-not-showing-data)</sub>

**Comment by ObservedObserver** [comment]
Hi, the correct way to use kernel computation engine is:

```py
pyg.walk(allsubs, use_kernel_calc=True)
```

Would you mind try the above code?
