### ISSUE TITLE
[Question]How to set  width & height parameter when you use pygwalker on flask app?

### ISSUE THREAD

**Issue by relakuman** [Kanaries/pygwalker#348]
hello.I use pygwalker on flask app. but display size is a little big, so I would like to resize it.
Though I tried width & height parameter to pyg.walk function, it didn't work. Is there any way to resize it?

Code)
    df = pd.read_sql(sql,engine)

    # Get Pygwalker as html
    html_str = pyg.walk(df, return_html=True, show_cloud_tool=False, dark='dark', width=800,height=400,scrolling=True)

    return templates.TemplateResponse("pygwalker.html",{"request": request, "html_str": html_str})

**Comment by longxiaofei** [comment]
try it, in your template file: `pygwalker.html`.

```
<div style="width: 1000px; height: 900px; overflow-y: auto;">
{{ html_str }}
</div>
```

**Comment by longxiaofei** [comment]
The height of grphic-walker is fixed, so if the parent container height is too small, scroll bars will inevitably appear, otherwise grphic-walker cannot be used completely.
