### ISSUE TITLE
Create  calculated measure in Pygwalker

### ISSUE THREAD

**Issue by longxiaofei** [Kanaries/pygwalker#353]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to flexibly create a calculated field in the UI.

**Describe the solution you'd like**
I can create a field and describe the results of this field through sql, like superset.

**Describe alternatives you've considered**
not sure, I want to know other's suggestions.

**Comment by longxiaofei** [comment]
Related discussions: #207

**Comment by longxiaofei** [comment]
Hi, @353913575, @ddealwis09

Do you have any suggestions for this?

**Comment by Edu126** [comment]
I don't know if I'm misunderstanding but maybe this can work, https://github.com/Kanaries/graphic-walker/wiki/How-to-Create-Computed-field-in-Graphic-Walker

**Comment by longxiaofei** [comment]
@Edu126 Yes, I forgot to close this issue.

**Comment by wzrzt** [comment]
> I don't know if I'm misunderstanding but maybe this can work, https://github.com/Kanaries/graphic-walker/wiki/How-to-Create-Computed-field-in-Graphic-Walker

Is this function deleted in recent versions? My pygwalker dosn't have it 

<img width="893" alt="Image" src="https://github.com/user-attachments/assets/c3b22f79-b1ca-4f86-8c4a-705939584978" />

**Comment by longxiaofei** [comment]
Hi @wzrzt, Thanks for your feedback. 

Currently, it can only be used in kernel_computation mode.

```python
pyg.walk(dataset, kernel_computation=True)
```
