### ISSUE TITLE
[feat] Support JupyterLite notebooks

### ISSUE THREAD

**Issue by westurner** [Kanaries/pygwalker#36]
Users can work with pygwalker in (offline) Jupyter Notebooks

Does pygwalker already work w/ micropip and JupyterLite?

```python
%pip install pygwalker
```

- https://jupyterlite.readthedocs.io/en/latest/howto/configure/advanced/offline.html
- TST: JupyterLite nb:
  https://github.com/chmp/ipytest#related-packages

**Comment by Asm-Def** [comment]
Seems that it worked well with JupyterLite.

![JupyterLite](https://user-images.githubusercontent.com/8137814/221019220-aba45570-3450-4e8a-8365-7feffcb84a46.png)

but haven't tested with an offline archive yet.

**Comment by westurner** [comment]
Nice.

- [ ] DOC: README: add JupyterLite if there are tests

**Comment by evertoncolling** [comment]
@Asm-Def it used to work, but apparently it does not work anymore due to some util method that checks for updates using the `requests` library that does not work in Pyodide.

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/33816483/227778840-b4ad3626-1a84-42e0-ad0e-f961fed1d46e.png">

**Comment by westurner** [comment]
- https://pyodide.org/en/stable/usage/api/python-api/http.html
- https://news.ycombinator.com/item?id=30168491
- https://github.com/pyodide/pyodide/issues/3160#issuecomment-1262816982
  - https://github.com/koenvo/pyodide-http#supported-packages
    - [x] urlopen.
    - [x] requests.{...}
      - https://github.com/koenvo/pyodide-http/blob/main/pyodide_http/_requests.py
      - https://github.com/koenvo/pyodide-http/blob/main/pyodide_http/_core.py#L68 `def send` appears to wrap XHR 
  - https://github.com/emscripten-forge/requests-wasm-polyfill
    - Emscripten-forge is like conda-forge
    - https://pyodide.org/en/latest/usage/service-worker.html are Service Workers Web Workers?
    - https://github.com/koenvo/pyodide-http/issues/6
- https://github.com/pyodide/pyodide/issues/140

**Comment by Asm-Def** [comment]
> @Asm-Def it used to work, but apparently it does not work anymore due to some util method that checks for updates using the `requests` library that does not work in Pyodide.
> 
> <img alt="image" width="1467" src="https://user-images.githubusercontent.com/33816483/227778840-b4ad3626-1a84-42e0-ad0e-f961fed1d46e.png">

Resolved in https://github.com/Asm-Def/pygwalker/pull/8. Please have a try with `pygwalker>=0.1.6.2a0 --pre`.

**Comment by evertoncolling** [comment]
Sorry for the late reply. I can confirm it works fine with the latest updates 👍.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/33816483/229195671-cc5713fc-5978-427f-8790-4ceec2f56a2d.png">

**Comment by westurner** [comment]
Could still be added to the README.

Thanks!
