### ISSUE TITLE
Can I put two sets of Y-axis data on the same chart?

### ISSUE THREAD

**Issue by fiend19961** [Kanaries/pygwalker#368]
I wanna put two sets of Y-axis data on the same chart,  but I found that I couldn't do it with PygWlaker.

like this:
![combine](https://github.com/Kanaries/pygwalker/assets/51880334/f3e11208-b628-4e5a-a645-239ddc6fd48d)

**Comment by longxiaofei** [comment]
use `Measure names` and `Measure values`.

![image](https://github.com/Kanaries/pygwalker/assets/28337703/b36cae59-ef49-488e-b0e6-c616afca6b68)
