### ISSUE TITLE
[BUG] error with filters for quantitative fields with null values

### ISSUE THREAD

**Issue by didi9575** [Kanaries/pygwalker#381]
**Describe the bug**
I cannot apply a filter on a quantitative column if there are None values in this column.

**To Reproduce**
1. You can create a dataframe like this one : 
```
import pandas as pd
import pygwalker as pyg
df = pd.DataFrame(columns=["weight", "gender", "score"], data=[[None, None, 1115], [77.65, "M", 601], [78, "F", 800]])
pyg.walk(df)
```
1. Go to Visualization
2. Drop the quantitative field `weight` into Filters
3. You get the error "Something went wrong"

However, you don't get the error for the fields `gender` (Nominal) or `score` (no null values).

**Versions**
- pygwalker version: 0.3.20
- python version: 3.10.11

**Additional context**
I have a very large dataframe with a lot of columns, and I don't want to do a df.dropna() before executing the pyg.walk().

**Comment by longxiaofei** [comment]
This is a front-end computing bug.

You can use `pyg.walk(df, use_kernel_calc=True)` to fix it temporary.

`use_kernel_calc=True` wiil use duckdb to finish calculation, and it can process large datas.

In future versions, we will fix this bug.

**Comment by longxiaofei** [comment]
Hi @didi9575 , `pygwalker 0.4.0` already fixed it.

`pip install --upgrade --pre pygwalker`
