### ISSUE TITLE
pygwalker is wrongly interpreting a column as a date 

### ISSUE THREAD

**Issue by faerberf** [Kanaries/pygwalker#388]
for some columns, which have 5 to five digits values ( in int forma) pygwalker is interpreting them as dates. ( coming from a dataframe type "object")  how can I avoid the wrong interpretation of the column in pygwalker

**Comment by longxiaofei** [comment]
Pygwalker is getting ready to remove some logic for inferring field types.

For '5 to five digits values', could you give an example?

**Comment by longxiaofei** [comment]
Hi @faerberf , try `pygwalker 0.4.0` to fixit.

`pip install --upgrade --pre pygwalker`
