### ISSUE TITLE
Pygwalker in Streamlit Python 3.9

### ISSUE THREAD

**Issue by LeCodeEst** [Kanaries/pygwalker#389]
Hi, 

Has anyone tested pygwalker in streamlit with python 3.9 in amazon redshift?

Locally, the code runs well, but when deployed into the cloud, we get the below error.
All ideas appreciated, thanks!

ModuleNotFoundError: No Module named '_sqlite3'

**Comment by longxiaofei** [comment]
The dependency configuration of pygwalker cannot directly solve these problems.

It may be that your current Python environment is lacking dependencies related to SQLite.

I have searched for some answers on the internet, hoping it can help you:

```
1. Install the sqlite-devel package

yum install sqlite-devel

2. Recompile python
```
