### ISSUE TITLE
[BUG]Panels and sidebars may cause offset of draggable fields

### ISSUE THREAD

**Issue by Json-Woo** [Kanaries/pygwalker#4]
Top Panels and Left Sidebars always cause a strange offset while dragging pills from the field list, see the GIF

![Feb-20-2023 12-53-27](https://user-images.githubusercontent.com/8137814/220013675-064f4333-e303-4275-a111-3ad9d54390ed.gif)

**Comment by Asm-Def** [comment]
Feedback forwarded to submodule repo.

https://github.com/Kanaries/graphic-walker/issues/24#issue-1591138199

**Comment by longxiaofei** [comment]
Sorry, it fixed, but forgot to reply.

If this bug still exists, you can reopen this issue.
