### ISSUE TITLE
[BUG]  ERROR: Failed building wheel for duckdb

### ISSUE THREAD

**Issue by jshuadvd** [Kanaries/pygwalker#400]
**Describe the bug**
When attempting to install via `pip install pygwalker` I receive the following errors:

`ERROR: Failed building wheel for duckdb`
`ERROR: Could not build wheels for duckdb, which is required to install pyproject.toml-based projects`

**To Reproduce**
1. Run ` pip install pygwalker ` 
2. See error

**Expected behavior**
The library should install without issue.

**Screenshots**
<img width="1513" alt="Screenshot 2024-01-19 at 8 06 33 PM" src="https://github.com/Kanaries/pygwalker/assets/7577457/65938774-af79-4325-a1b6-1aa4c1ee888f">

**Versions**
- pygwalker version: 0.4.2
- python version: 3.12.1

**Comment by longxiaofei** [comment]
Currently, the latest released version of duckdb cannot run on python3.12.

You may need to use python3.11 to run Pygwalker(recommend).

Or you can also try to install the latest development version of duckdb: `pip install duckdb==0.9.3.dev2938`

**Comment by jshuadvd** [comment]
Thank you for the update. 

I have tried the suggestion of using the latest development version of duckdb, but unfortunately that does not work: `ERROR: pygwalker 0.4.2 requires duckdb==0.9.2, but you have duckdb 0.9.3.dev2938 which is incompatible.`

I will try with Python 3.11 and report back.

**Comment by anandakrishnankb** [comment]
I had the same issue while installing pygwalker.I switched to python v3.9 and the issue was solved.

**Comment by Marceau-h** [comment]
Hi, I had the same issue, maybe you could change the `requires-python` tag, it would prevent even trying to install (saying no versions of the package mathces the current python version)

**Comment by longxiaofei** [comment]
`pygwalker>=0.4.7` already support `duckdb==0.10.0`.


pygwalker currently supports running on `python3.12`

**Comment by jshuadvd** [comment]
This is now working for me @longxiaofei thank you for your help. I will close now :)
