### ISSUE TITLE
[Feat] Support for Polars

### ISSUE THREAD

**Issue by alexk101** [Kanaries/pygwalker#41]
Thank you for this wonderful data analysis project! It is going to be quite helpful for a lot of non-technical people in our lab. I do have a suggestion for a feature, which may or may not be feasible, but integrating [Polars](https://github.com/pola-rs/polars) support for this tool would be a wonderful addition. Its programming interface is quite similar to that of Pandas, but has quite a few differences in order to optimize the library for speed and performance. It makes working with a lot of our very large datasets in python much quicker.

**Comment by jordan-carson** [comment]
this can be done by converting polars to pandas, but I agree polars support would be best.

```python
import polars as pl
import pygwalker as pyg

data = pl.read_csv(r"../file.csv")
data = data.to_pandas()

pyg.walk(data)
```

**Comment by Asm-Def** [comment]
@alexk101 @jordan-carson 
It's now supported in pr #57 from @0warning0error.
Please try `pip install pygwalker>=0.1.4.7a0` to experience it.

**Comment by alexk101** [comment]
@Asm-Def 
Awesome! Thanks for the fast turn around time!

**Comment by 0warning0error** [comment]
@Asm-Def I deleted **graphic-walker.iife.js** by mistake. If you want to experience it, remember to check it.

**Comment by alexk101** [comment]
@Asm-Def 
Awesome! Thanks for the fast turn around time!
