### ISSUE TITLE
pygwalker 0.4.5 error: VM1227:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<html><tit"... is not valid JSON

### ISSUE THREAD

**Issue by Renaldy002** [Kanaries/pygwalker#429]
pygwalker 0.4.5
python 3.9.0
streamlit 1.30.0

I want to show chart only on streamlit so I used this code I found

```
renderer = get_pyg_renderer(chart_data,vis_spec)
renderer.render_pure_chart(0)
```

or

```
renderer = get_pyg_renderer(chart_data)
renderer.render_explore()
```

but it got error VM1227:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<html><tit"... is not valid JSON

when I try the different method of showing chart it works but I can't show chart only by using this method

```
pyg_html = pyg.to_html(chart_data,spec=vis_spec)
components.html(pyg_html,scrolling=True,height=500)
```

![pygwalker 1](https://github.com/Kanaries/pygwalker/assets/80593054/b7abb4a9-8298-4159-8cba-6dea180a05c9)
![pygwalker 2](https://github.com/Kanaries/pygwalker/assets/80593054/7cf190e4-d814-49b2-8da5-78e1ef1610cc)
![pygwalker 3](https://github.com/Kanaries/pygwalker/assets/80593054/f016482b-1c44-43c6-b525-f4d5682329b2)

**Comment by longxiaofei** [comment]
add code: 
```python
from pygwalker.api.streamlit import init_streamlit_comm

init_streamlit_comm()
```

In the next version of pygwalker, `init_streamlit_comm` will be loaded implicitly.

**Comment by Renaldy002** [comment]
okaay it works for me, thank you so much
