### ISSUE TITLE
How to get two coaxial pieces of data to be displayed together instead of divided into two views?

### ISSUE THREAD

**Issue by jnhzzzk** [Kanaries/pygwalker#43]
How to get two coaxial pieces of data to be displayed together instead of divided into two views?

Such as a dataset that there is the same X-axis of date but two attribute

**Comment by Asm-Def** [comment]
For now, you can make it with pandas APIs.

Suppose we have a dataframe `df` with fields `A`, `B` and `date`, and now we want an overlay view of `A-date` and `B-date`.

Then you can use `df = df.melt(value_vars=['A', 'B'])` to unpivot `A` and `B` into one column

**Comment by d505** [comment]
Hi, I am interested in contributing to this Issue.

However, I am new to this repository.

I understand the modifications described, but I am not sure where I should write the procedure. Could you please give me a guide here?

**Comment by Asm-Def** [comment]
> Hi, I am interested in contributing to this Issue.
> 
> However, I am new to this repository.
> 
> I understand the modifications described, but I am not sure where I should write the procedure. Could you please give me a guide here?

@d505 Sorry for the late reply, I didn't notice this comment. it's now a feature of https://github.com/Kanaries/Graphic-Walker, you can view it here https://github.com/Kanaries/graphic-walker/pull/61

**Comment by Julius-Plehn** [comment]
Hi there, I think I am having the same issue with a dataset of mine. 
What I would like to achieve is multiple lines for the same X and Y Axis without creating new plots for each of this "categories". When I try to put this dataset into a single plot with a single attribute for the X-Axis and the Y-Axis and I try to make the distinction of two categories with the Color and the Shape view, the coloring and shaping looks fine but only a single line is plotted. 

When I put another item on the X-Axis I get two plots with one line plot in each and this is kind of the plot I would like to have, but in a single plot. Maybe there should be a toggle to select either of those two variants?

I hope this description makes sense, thanks for any help!

**Comment by longxiaofei** [comment]
This feature is in the draft stage in [Graphic-Walker](https://github.com/Kanaries/Graphic-Walker), the developer of Graphic-Walker told me it will be released soon.
