### ISSUE TITLE
[BUG] The data in 'view data' is wrong when setting filters

### ISSUE THREAD

**Issue by DonYum** [Kanaries/pygwalker#447]
**Describe the bug**
I set a range filter and render a bar graph, however the data in 'view data' is wrong.

**To Reproduce**
1. set a range filter
2. render a bar graph
3. click 'View Data' on a bar
4. check the data, There will be some data out of the filter

**Expected behavior**
The data in 'view data' should be in range of the filter.

**Screenshots**
![image](https://github.com/Kanaries/pygwalker/assets/1471864/55bf6704-d982-476f-a138-60c1f9694c83)

![image](https://github.com/Kanaries/pygwalker/assets/1471864/1600e689-883d-477f-af98-3f7ba2e9a992)

**Versions**
- pygwalker version: 0.4.6
- python version: 3.8
- browser: chrome latest

**Additional context**

**Comment by longxiaofei** [comment]
Thanks for your feedback.

We'll fix it within 7 days.

**Comment by longxiaofei** [comment]
fixed it.

`pip install --upgrade pygwalker`
