### ISSUE TITLE
[BUG] Interpret Data meet Oops!

### ISSUE THREAD

**Issue by DonYum** [Kanaries/pygwalker#448]
**Describe the bug**
I render a bar graph, when click 'Interpret Data' meet a Oops bug.

**To Reproduce**
1. render a bar graph
2. click 'Interpret Data' on a bar, There will be a Oops Error

**Expected behavior**

**Screenshots**
![image](https://github.com/Kanaries/pygwalker/assets/1471864/81f1fce1-5009-4dd4-a119-61f33f6b17c0)

![image](https://github.com/Kanaries/pygwalker/assets/1471864/788bfad9-f9d0-469a-a3cd-53d0fc4780d0)

**Versions**
- pygwalker version: 0.4.6
- python version: 3.8
- browser: chrome latest

**Additional context**

**Comment by longxiaofei** [comment]
It seems that the kernel calculation is not compatible with the old workflow.

We'll fix it within 7 days.

Thanks!

**Comment by longxiaofei** [comment]
fixed it.

`pip install --upgrade pygwalker`
