### ISSUE TITLE
ASK AI should work with open source self hosted/cloud hosted LLMs in open source pygwalker

### ISSUE THREAD

**Issue by rishabh-dream11** [Kanaries/pygwalker#454]
**Is your feature request related to a problem? Please describe.**
I am unable to integrate or use Amazon Bedrock, Azure GPT, Gemini or my own llama 2 LLM for the ASK AI feature.

**Describe the solution you'd like**
Either I should have the option to remove the real state used by the ASK AI bar in the open source PyGwalker or I should be able to integrate custom LLM endpoints.

**Comment by ObservedObserver** [comment]
Thank you for your feedback. Currently, we do not support different llm endpoints or the option to remove the real state used by the ASK AI bar in PyGwalker. We only provide our own [API for PyGwalker](https://kanaries.net/home/pygwalker). While we appreciate your suggestion, we don't have plans to implement these features at the moment.

**Comment by rosmur** [comment]
since this is open source, we can fork and edit right? could you or someone please provide guidance on which components support this feature?

**Comment by rishabh-dream11** [comment]
@ObservedObserver Can you keep the issue open for others to submit PR on it.

**Comment by ObservedObserver** [comment]
Hi @rosmur @rishabh-dream11.

I will keep the issue open and welcome to make PRs. If your are interested implement it, here is how you can develop:

What ask viz does it use LLM to generate a DSL of graphic walker, the DSL's JSON schema can be found at https://graphic-walker.kanaries.net/chartinfo.json

If you connect pygwalker with custom LLM, you build a function (metas, query) => DSL, and pass it to pygwalker. We will add a func parameter for pygwalker in next release which allows you to put your customized function there.

**Comment by longxiaofei** [comment]
`pip install --pre --upgrade pygwalker`

pygwalker already support custom ask callback function. 

```python
from typing import List, Dict, Any

# metas: [{"dragId":"gw_8ffA","fid":"work yes or not","name":"work yes or not","basename":"work yes or not","semanticType":"nominal","analyticType":"dimension"}]
# query: register count per season
# return: refer https://graphic-walker.kanaries.net/chartinfo.json
def ask_callback(metas: List[Dict[str, Any]], query: str) -> Dict[str, Any]:
    return {}

pyg.walk(df, custom_ask_callback=ask_callback)
```

related pr: #477
