### ISSUE TITLE
Question: How to hidden mode function

### ISSUE THREAD

**Issue by relakuman** [Kanaries/pygwalker#455]
Hello
I display pygwalker on web app.
I use latest version(0.4.6 ).
 I don't have to display mode function  because I always use only walker mode.
Is it possible to hidden mode function?

![pygwalker](https://github.com/Kanaries/pygwalker/assets/59464306/f62ab0e9-adf5-446a-a6d7-c19ab0729d50)

**Comment by ObservedObserver** [comment]
Thanks for the feedback.

I think there can be two propsal for this:

## 1. Extra parameters
Usage example:
```py
pygwalker.walk(df, mode='walker', enable_mode_option=True)
```
`mode` can be choosen from `walker` and `enable_mode_option` and it is the default value of selection.
`enable_mode_option` decide whether allow the end users to switch the mode.

## 2. Expose more compoments
For now,  pygwalke wrap all features and components from graphic walker together as a simple API, `walk`. But we can expose more raw components from graphic walker to allow developers to have more control of pygwalker.

usage example:
```py
# walker component
pygwalker.walk(df)

# renderer component
pygwalker.render(df)

# table component
pygwalker.table(df)
```

**Comment by ObservedObserver** [comment]
Besides, @relakuman would you like to share what web app framework you are using to host pygwalker?

**Comment by relakuman** [comment]
@ObservedObserver
Thank you for your reply.
I'm using FastAPI to host pygwalker.
I tried "mode" and "enable_mode_option",but it didn't work.
I also tried them on Jupyter lab, but the result was same.
Did I miss something?
![pygwalker2](https://github.com/Kanaries/pygwalker/assets/59464306/cd577218-88a3-4dc6-8bcc-546d9325ff78)

**Comment by ObservedObserver** [comment]
Hi, the apply above are just proposal, we havn't implement them yet. This feature will be marked P1, which will be published in one week.

**Comment by relakuman** [comment]
@ObservedObserver 
Sorry for my misunderstanding! I appreciate you for the release announcement of new function.

**Comment by longxiaofei** [comment]
@relakuman 

`pip install --upgrade pygwalker`

`pyg.walk`will not have mode option.
