### ISSUE TITLE
[DEV-688] [BUG] pygwalker with snowflake import error

### ISSUE THREAD

**Issue by ObservedObserver** [Kanaries/pygwalker#456]
ImportError: cannot import name 'string_types' from 'sqlalchemy.util.compat' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sqlalchemy/util/compat.py)

<sub>[DEV-688](https://linear.app/kanaries/issue/DEV-688/[bug]-pygwalker-with-snowflake-import-error)</sub>

**Comment by longxiaofei** [comment]
Use the snowflake version specified by pygwalker.

`pip install pygwalker[snowflake]`
