### ISSUE TITLE
Need to disable external api server calls

### ISSUE THREAD

**Issue by JeevankumarDharmalingam** [Kanaries/pygwalker#458]
Fetch Calls are requested using Streamlit
1.  GET - https://cdn.segment.com/v1/projects/iCkMy7ymtJ9qYzQRXkQpnAJEq7D4NyMU/settings
2. POST - https://api.segment.io/v1/t

Note : In Config.json set privacy='offline'

Is there a way to disable these request calls

**Comment by longxiaofei** [comment]
```
GET - https://cdn.segment.com/v1/projects/iCkMy7ymtJ9qYzQRXkQpnAJEq7D4NyMU/settings
POST - https://api.segment.io/v1/t
```

These requests are sent by streamlit. You can refer to streamlit's documentation.
