### ISSUE TITLE
There are a lot of great st components scattered on github, why not merge into the main st branch?

### ISSUE THREAD

**Issue by DonYum** [Kanaries/pygwalker#466]
There are a lot of great streamlit components scattered on github, why not merge into the main streamlit branch?

**Comment by ObservedObserver** [comment]
Sorry, I think it is not a related issue for pygwalker. I am going to close it.

But for streamlit third part components, it more flexiable for developers to choose by them self, not to put everything in streamlit which will lead to large package size issues.
