### ISSUE TITLE
DataFrame's column names display Unicode

### ISSUE THREAD

**Issue by freedomgod** [Kanaries/pygwalker#49]
# DataFrame's column names display Unicode
I am using JupyterLab. I encountered an encoding problem when importing a data set. The column names of the DataFrame contain Chinese, but the Chinese is displayed as Unicode. The strange thing is that the value of the field also contains Chinese, but it can be displayed normally.
<img width="772" alt="DXTRyHFcaW" src="https://user-images.githubusercontent.com/59652488/221740595-5ae81295-b90c-43bd-a747-9eecceeef7db.png">

**Comment by Asm-Def** [comment]
fixed in pr #51 and will be released in 0.1.4.5.
