### ISSUE TITLE
[BUG] data view throws error when column contains the same number

### ISSUE THREAD

**Issue by wzherwa** [Kanaries/pygwalker#507]
**Describe the bug**
whenever you load a data with a least one column that contains the same number (doesn't matter if integer or float) - also with one row only (!), it throws the following error:
Out of Range Error: cannot take logarithm of zero
and does not show the respective data and histograms.

**To Reproduce**
just load any data with only one row OR a column that contains the same number ... 

**Expected behavior**
in that case, provide in the statistics only this number (and don't try binning/creating histogram)

**Screenshots**

![image](https://github.com/Kanaries/pygwalker/assets/150339984/b0ce60ef-c2db-48d7-a97f-e9cd3abaeafb)

**Versions**
- pygwalker 0.4.7
- streamlit 1.32.2
- python 3.11.7
- browser: safari, chrome, edge ...

**Additional context**
Please fix asap ... this is a very "surprising" bug (!)

**Comment by longxiaofei** [comment]
@wzherwa 

Thanks for  your feedback. I reproduced it.

This bug will be reproduced when the data in a certain column is all 0, we will fix it as soon as possible.
