### ISSUE TITLE
[BUG] Index out of bounds on reading a dataframe

### ISSUE THREAD

**Issue by RaulVS14** [Kanaries/pygwalker#516]
**Describe the bug**
Trying to read in 10000+ row dataframe. Getting an error:
`IndexError: index 10001 is out of bounds for axis 0 with size 10001`

```
Traceback:
File "/app/app.py", line 83, in <module>
    main()
File "/app/app.py", line 78, in main
    analytics_tab()
File "/app/tabs/pygwalker_analytics/analytics_tab.py", line 146, in analytics_tab
    renderer.render_explore()
File "/usr/local/lib/python3.11/site-packages/pygwalker/api/streamlit.py", line 201, in render_explore
    html = self._get_html(**{"defaultTab": default_tab})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pygwalker/api/streamlit.py", line 147, in _get_html
    return self._get_html_with_params_str_cache(params_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/cachetools/__init__.py", line 737, in wrapper
    v = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pygwalker/api/streamlit.py", line 119, in _get_html_with_params_str_cache
    props = self.walker._get_props("streamlit")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pygwalker/api/pygwalker.py", line 530, in _get_props
    "fieldMetas": self.data_parser.field_metas,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pygwalker/data_parsers/base.py", line 138, in field_metas
    duckdb.register("pygwalker_mid_table", self._duckdb_df)
```

**Versions**
- pygwalker version: 0.4.7
- python version: 3.11.8

**Additional context**
Similar issue was mentioned in: https://github.com/duckdb/duckdb/issues/10750
Recently DuckDB released [PR](https://github.com/duckdb/duckdb/pull/10768) to fix that issue with: [0.10.1 Bugfix Release ](https://github.com/duckdb/duckdb/releases/tag/v0.10.1).

I think this would be solved with DuckDB version requirement update from 0.10.0 -> 0.10.1

**Comment by longxiaofei** [comment]
Thanks for your feedback.

I just released a pre-release to fix it: `pip install pygwalker==0.4.8a11`.

Or you can force update the duckdb version and ignore the dependency warning of pygwalker(0.4.7).

**Comment by RaulVS14** [comment]
I will use the pre-release. Ignoring dependency warning isn't available choice, because I install with requirements.txt and pip refuses to install.

One thing I noticed while trying it out is that for some reason displayed view goes dark mode by default, even though I have light mode used in streamlit.

**Comment by longxiaofei** [comment]
Did you specify a streamlit theme?

example:

```
[theme]
base="light"
```

**Comment by RaulVS14** [comment]
Yes, I have these exact lines in my config file.

**Comment by ObservedObserver** [comment]
pygwalker by default use system appearance. In your case, it seems your system is dark theme while your streamlit is light theme. You can change the appearance of pygwalker:
```py
import pygwalker as pyg

pyg.walk(df, appearance='light')
```

**Comment by RaulVS14** [comment]
Great, thanks for explaining! Problem solved :)
