### ISSUE TITLE
How to switch the language pack to Chinese

### ISSUE THREAD

**Issue by zxdmrg** [Kanaries/pygwalker#519]
How to switch the language pack to Chinese

**Comment by ObservedObserver** [comment]
pygwalker is a python wrapper of graphic walker. Except all offical parameter in pygwalker document, you can pass extra paramter to graphic walker in python directly. According to [graphic walker i18n doc](https://github.com/Kanaries/graphic-walker?tab=readme-ov-file#customize-i18n)

```py
pyg.walk(df, i18nLang="zh")
```

**Comment by zxdmrg** [comment]
Solved my problem. Thank you very much
