### ISSUE TITLE
[BUG] Clicking `Copy to Clipboard` button causes a JavaScript error

### ISSUE THREAD

**Issue by BHznJNs** [Kanaries/pygwalker#542]
**Describe the bug**
I tried to run the `examples/dash_demo.py`, when I opened the `Code Export` dialog and tried to copy the code with the `Copy to Clipboard` button, it does not work. When I opened the browser console, it showed a JavaScript error.

**To Reproduce**
1. Open Dataset with Pygwalker
2. Click on the `export_code` button
3. Click the `Copy to Clipboard` button in the `Code Export` dialog
4. The copying operation does not work and shows an error in the browser console

**Expected behavior**
Able to copy the code by clicking the `Copy to Clipboard` button

**Screenshots**

Clicking the `Copy to Clipboard` button
![Clicking the `Copy to Clipboard` button](https://github.com/Kanaries/pygwalker/assets/67158072/62cbf91d-06d9-4b9b-a1a3-2758c1666536)

Shows an JavaScript TypeError in the browser console
![Shows an JavaScript TypeError in the browser console](https://github.com/Kanaries/pygwalker/assets/67158072/055a7119-f1f8-4bb4-aaeb-14d41928ac1c)

**Versions**
- pygwalker version: 0.4.8.3
- python version: 3.10.7
- browser: Firefox 125.0.3 on Windows11 x86_64

**Additional context**
With the [MDN Permissions API docs](https://developer.mozilla.org/zh-CN/docs/Web/API/Permissions/query), I assumes the bug is occured by the implement difference between browsers.
In the line 45 of source code file `app\src\components\codeExportModal\index.tsx`, it used name `clipboard-read` as PermissionName. In this [w3c PR](https://github.com/w3c/clipboard-apis/pull/132), the clipboard-read permission was removed.
In [this page](https://searchfox.org/mozilla-central/source/dom/webidl/Permissions.webidl#10), it seems that the `clipboard-read` field is not in the PermissionName enum for Firefox, while in [this page](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/third_party/blink/renderer/modules/permissions/permission_descriptor.idl), it seems that the `clipboard-read` is a non-standard field in the PermissionName enum for Chromium.

**Comment by longxiaofei** [comment]
Hi, @BHznJNs 

Thanks for your feedback.

It seems that there are some bugs when check permissions of clipboard.

If you're willing, you might try to fix it.

Looking forward to your PR.

```
function name: copyToCliboard
code location: app\src\components\codeExportModal\index.tsx  - line:44
```
