### ISSUE TITLE
pygwalker cannot be rendered

### ISSUE THREAD

**Issue by 3dsf0sge** [Kanaries/pygwalker#545]
![( O4{0{APDJ64}58 M B4ZH](https://github.com/Kanaries/pygwalker/assets/96034897/29c2c492-7d24-4d01-beab-b6b073018cbd)
![KZD(%E8C`@A(R LV4CZ7KL3](https://github.com/Kanaries/pygwalker/assets/96034897/131d016e-b7d1-4b9a-988d-46ea89d38b1d)

**Comment by longxiaofei** [comment]
Hi @3dsf0sge , thanks for your feedback.

Try this, does it work?

```python
import pygwalker as pyg
import pandas as pd

df = pd.read_csv("https://kanaries-app.s3.ap-northeast-1.amazonaws.com/public-datasets/bike_sharing_dc.csv")

walker = pyg.walk(df)
```

**Comment by 3dsf0sge** [comment]
@longxiaofei Thanks for the reply, but there are still bugs, I'm looking into it.
![image](https://github.com/Kanaries/pygwalker/assets/96034897/dc64e814-26f9-4978-8a73-a0cb4bcc6c77)

**Comment by longxiaofei** [comment]
@3dsf0sge 

After you execute `pyg.walk(df)` in jupyter, open the browser's developer tools and check the console for errors.

another try:

```python
import pygwalker as pyg
import pandas as pd


df = pd.read_csv("https://kanaries-app.s3.ap-northeast-1.amazonaws.com/public-datasets/bike_sharing_dc.csv")

with open("pyg_demo.html", "w", encoding="utf-8") as f:
    html = pyg.to_html(df)
    f.write(html)
```

then open `pyg_demo.htm` in the browser.

**Comment by 3dsf0sge** [comment]
I tried it at your suggestion, but it didn't work out。If it's convenient for you, can you help me debug it remotely。
![image](https://github.com/Kanaries/pygwalker/assets/96034897/2d8118f3-d123-4974-867a-15cf480c196c)
![image](https://github.com/Kanaries/pygwalker/assets/96034897/7795b7b2-4d75-4511-a1a8-efafcbf5164e)

**Comment by 3dsf0sge** [comment]
@longxiaofei 
I'm running successfully in pycahrm, thanks for your help!
![image](https://github.com/Kanaries/pygwalker/assets/96034897/0dc7b607-7c0e-49fb-bb3e-3450bb2e60cb)
![image](https://github.com/Kanaries/pygwalker/assets/96034897/0f65aebb-184e-406a-938e-8e36b71b0e38)

**Comment by longxiaofei** [comment]
Hi @3dsf0sge 

You can try it:

```
pip install --upgrade jupyterlab
pip install --upgrade ipywidgets
```

Then restart your jupyter notebook.

**Comment by 3dsf0sge** [comment]
> Hi @3dsf0sge
> 
> You can try it:
> 
> ```
> pip install --upgrade jupyterlab
> pip install --upgrade ipywidgets
> ```
> 
> Then restart your jupyter notebook.

Successful operation, thank you very much for your help!
![image](https://github.com/Kanaries/pygwalker/assets/96034897/858a8db8-adce-4ae3-a9f4-2715aa20fbd3)
