### ISSUE TITLE
Pygwalker cannot render too much data

### ISSUE THREAD

**Issue by heqi201255** [Kanaries/pygwalker#546]
I was trying to plot my data using Pygwalker, the data is a csv file about 467MB with shape (3682080, 12), my code is like:
```py
from pygwalker.api.streamlit import StreamlitRenderer
import pandas as pd
import streamlit as st

# Adjust the width of the Streamlit page
st.set_page_config(
    page_title="Use Pygwalker In Streamlit",
    layout="wide"
)

# Add Title
st.title("Use Pygwalker In Streamlit")

# You should cache your pygwalker renderer, if you don't want your memory to explode
@st.cache_resource
def get_pyg_renderer() -> "StreamlitRenderer":
    df = pd.read_csv("/data.csv")
    # If you want to use feature of saving chart config, set `spec_io_mode="rw"`
    return StreamlitRenderer(df, kernel_computation=True)


renderer = get_pyg_renderer()

renderer.explorer()
```
I tried to use pygwalker inside jupyter and via streamlit, both gave me the error "The query returned too many data entries, making it difficult for the frontend to render. Please adjust your chart configuration and try again."

Screenshot:
![Screenshot 2024-05-13 at 14 56 56](https://github.com/Kanaries/pygwalker/assets/33139237/2b1b9588-2035-499a-b985-2e4d9cb9ed3b)

The visualization is stuck at loading, and got a timeout message afterwards. Is there any workaround to render my data? What chart configuration should I adjust?

**Comment by longxiaofei** [comment]
Hi @heqi201255 

what's output?

```python
print(df['t'].value_counts().count())
````

If it is larger than 1000k, it will be difficult for the frontend to render 1000k pieces of data into a chart.

**Comment by longxiaofei** [comment]
Since I don't know what the data fields themselves mean, I can't give good advice at the moment.
