### ISSUE TITLE
Embedding Pygwalker in a Streamlit Application which is running behind apache server as a proxy

### ISSUE THREAD

**Issue by Vulum** [Kanaries/pygwalker#552]
My steamlit application, containing Pygwalker is running behind apache server serving as proxy server. Now, when pygwalker code is added, my application kept on sending POST request to this internal url `/_stcore/_pygwalker/comm/00061893edcc579dRulOIZVX2Um9TD8h`. `00061893edcc579dRulOIZVX2Um9TD8h` varies on every POST request.

Why this POST request? Is this url serving static files for pygwalker or some internal pygwalker API?

**Comment by Vulum** [comment]
Never mind, this just require some few lines of appropriate proxying in apache2 config file

**Comment by longxiaofei** [comment]
Hi @Vulum 

This request works for pygwalker frontend and backend communication.

For example, use duckdb to calculate  the data needed for charts.
