### ISSUE TITLE
[BUG] pygwalker bug report

### ISSUE THREAD

**Issue by kerwinkfs** [Kanaries/pygwalker#556]
**Describe the bug**

**To Reproduce**
1. clone repro
2.  innstalled dependecies 

**Expected behavior**
Run application.

**Screenshots**

**Versions**
- pygwalker version: 0.4.8.5
- python version: 3.10
- browser: Chrome

**Additional context**
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kerwinstanley/aialtruists/dev/aialtruistclone/pages/dataanalyze/pygwalker/templates/dist/pygwalker-app.iife.js'

**Comment by longxiaofei** [comment]
refer it: https://pygwalker-docs.vercel.app/installation#local-development

```bash
cd app
 
yarn install
 
yarn build
```
