### ISSUE TITLE
Text color in dark mode

### ISSUE THREAD

**Issue by hima2b4** [Kanaries/pygwalker#56]
This is a wonderful library.
I am very excited after a long time.
It seems to be enough to get an overview of the dataset.
Thank you.

Thanks also for the dark mode update.
I have only one request.
When in dark mode, the text color is not visible, perhaps because it is black. I would appreciate it if you could improve it.

![DarkMode](https://user-images.githubusercontent.com/90017759/222054644-dc506345-9b67-46b7-a557-18ee4bc552bf.JPG)

**Comment by hima2b4** [comment]
Thanks for the confirmation and reply.
The problems that are arising are very small compared to what this library can do. It has served us well enough. Thank you.

**Comment by Asm-Def** [comment]
Glad to have your approval 😄
