### ISSUE TITLE
Questions Regarding Integration of PygWALKER Chat Functionality in Streamlit Without Kanaries API Key

### ISSUE THREAD

**Issue by wuhuanyan** [Kanaries/pygwalker#570]
If I want to use the chat functionality of PygWALKER in Streamlit, do I necessarily need to use the kanaries_api_key?
Can I integrate other GPT models?

**Comment by ObservedObserver** [comment]
Yes, related discussion: https://github.com/Kanaries/pygwalker/issues/454
