### ISSUE TITLE
[BUG] Param "dark" not work

### ISSUE THREAD

**Issue by Erimus-Koo** [Kanaries/pygwalker#571]
`dark` does not work in the current version. 
It's worked well in older versions. I didn't change my code and just run an old notebook.
I can only click the theme buttons to change the theme, and my choice won't be remembered.

Name: pygwalker
Version: 0.4.8.9

Python 3.9 Jupyter Lab

**Comment by ObservedObserver** [comment]
Hi @Erimus-Koo, thanks for reporting this issue.

It looks like the dark parameter has been replaced with appearance in the current version. You can update your code like this:

```py
pyg.walk(df, appearance="dark")
```

We'll address this in the next release to ensure backward compatibility or add a warning.

**Comment by Erimus-Koo** [comment]
想试来着
但我刚好用pip重装了一下jupyter lab，现在跑不通了，是有啥依赖我漏装了嘛？
![image](https://github.com/Kanaries/pygwalker/assets/17139670/11ac0659-9697-4953-baab-ba7376df875d)

**Comment by Erimus-Koo** [comment]
```
 jupyter --version
Selected Jupyter core packages...
IPython          : 8.25.0
ipykernel        : 6.29.4
ipywidgets       : 8.1.3
jupyter_client   : 7.4.9
jupyter_core     : 5.7.2
jupyter_server   : 2.14.1
jupyterlab       : 3.6.7
nbclient         : 0.10.0
nbconvert        : 7.16.4
nbformat         : 5.10.4
notebook         : 6.5.7
qtconsole        : not installed
traitlets        : 5.14.3
```

Python 3.12.1
pygwalker 0.4.8.9

---

More info 👆🏻

**Comment by longxiaofei** [comment]
Hi @Erimus-Koo 

This may be caused by the inconsistent jupyter extension versions that jupyterlab and ipywidgets depend on.

```
pip install --upgrade jupyterlab
pip install --upgrade ipywidgets
```

Then restart jupyter lab.

**Comment by Erimus-Koo** [comment]
```
pip install --upgrade ipywidgets
```
`ipywidgets` helps, thanks.
Maybe this could be included in the `readme.md` or FAQ.

BTW, `appearance` worked. 

And I've noticed that the spec has a new `json` version, that's great.
Is there a changelog, I'm afraid for missing something new.
