### ISSUE TITLE
Add bearer token to the api call 

### ISSUE THREAD

**Issue by JeevankumarDharmalingam** [Kanaries/pygwalker#575]
Thanks for the demo , there's one more request in below api is called from pygwalker
http://127.0.0.1:8080/_pygwalker/comm/test0

Is it possible to add bearer token in the header of this api call ?

**Comment by JeevankumarDharmalingam** [comment]
In below refer it: https://github.com/Kanaries/pygwalker/blob/main/examples/web_server_demo.py

**Comment by longxiaofei** [comment]
Under the same domain name, you can store the token into cookie and obtain the token from the cookie when requesting the apis of pygwalker.

Or maybe I misunderstood your needs, could you provide us with details on how you would use this feature?
