### ISSUE TITLE
How do I get data in vis_spec and save it to a variable (pygwalker.api.streamlit )?

### ISSUE THREAD

**Issue by andrec84j** [Kanaries/pygwalker#580]
Streamlit
from pygwalker.api.streamlit import StreamlitRenderer

Is it possible to take the data from vis_spec after finishing the construction of a graph and save the data in a variable?

**Comment by longxiaofei** [comment]
Hi @andrec84j ,This feature is not currently supported.

I'm interested to know what things you would be able to accomplish with this feature. Could you please share some details?

**Comment by longxiaofei** [comment]
Hi, @andrec84j 

pygwalker already support this feature in `pygwalker==0.4.9.4a0`.

```python
from pygwalker.api.streamlit import StreamlitRenderer
import pandas as pd
import streamlit as st

@st.cache_resource
def get_pyg_renderer() -> "StreamlitRenderer":
    df = pd.read_csv("xxx")
    return StreamlitRenderer(df)

renderer = get_pyg_renderer()

event = renderer.explorer()

print(event)
```

**Comment by zd1990** [comment]
hi,@longxiaofei

**Comment by zd1990** [comment]
hi,@longxiaofei
Is it possible to obtain the last filtered dataframe object in Gradio?
`
    df = pd.DataFrame(dj)
    pyg_app = get_html_on_gradio(df, spec="./viz-config.json",spec_io_mode="rw",default_tab="data")
    gr.HTML(pyg_app)
`

**Comment by longxiaofei** [comment]
Hi @zd1990 

Do you want to get the filtered data by operating in the data tab?

This feature is not currently supported, but I am developing it .

**Comment by zd1990** [comment]
@longxiaofei 
Yes, thanks for your work

**Comment by andrec84j** [comment]
> Hi @andrec84j ,This feature is not currently supported.
> 
> I'm interested to know what things you would be able to accomplish with this feature.
> 
> Could you please share some details?


Hello @longxiaofei
By achieving this, you add the functionality to save and share the analysis with other customers without the need to send or load the viz_spec.

I created an area to save the viz_spec with the possibility of sharing but it would be interesting for the user to be able to save and share without worrying about copying and pasting the PyGWalker Code

![image](https://github.com/user-attachments/assets/b20e6b55-c410-4a39-9f33-859fcda45c24)

**Comment by zhentai-SMU** [comment]
> Hi [@zd1990](https://github.com/zd1990)
> 
> Do you want to get the filtered data by operating in the data tab?
> 
> This feature is not currently supported, but I am developing it.

Thank you for your contribution. Has this feature been implemented?
