### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/pygwalker-main/pygwalker/templates/dist/pygwalker-app.iife.js'

### ISSUE THREAD

**Issue by duanbo320** [Kanaries/pygwalker#611]
run
import pygwalker as pyg
import pandas as pd
FileNotFoundError: [Errno 2] No such file or directory: '/pygwalker-main/pygwalker/templates/dist/pygwalker-app.iife.js'

**Comment by longxiaofei** [comment]
Hi, @duanbo320, thanks for your feedback, how did you install pygwalker? pip? conda?

**Comment by longxiaofei** [comment]
Based on the error message, it appears that the code did not import the pygwalker package from site-packages.

The path mean that you cloned the pygwalker project and attempted to import pygwalker from the pygwalker project's root directory.

I'm not sure if my guess is correct.
