### ISSUE TITLE
Unique count on duplicated data set.

### ISSUE THREAD

**Issue by dickhfchan** [Kanaries/pygwalker#615]
I got a dataset with a lot of duplicated rows. It comes from a master table with a few one to many related tables. When we links these tables together to product a simple table/spreadsheet. There are a lof duplications. 

In Excel pivot table, we can use the unique count to remove duplications. The same feature is avaiable in PowerBI. 

Do you have the same unique count in Pygwalker?

**Comment by longxiaofei** [comment]
Hi, @dickhfchan  sorry for the late reply.

It's not sure to me whether computed fields solve your needs.

example:

<img width="1155" alt="22" src="https://github.com/user-attachments/assets/d3c0a780-b6ae-4b62-9a3e-e49bd0014b44">

<img width="1059" alt="11" src="https://github.com/user-attachments/assets/f086b876-41c8-4918-8c72-0b5979857a4b">

<img width="1085" alt="image" src="https://github.com/user-attachments/assets/cef12130-451f-42d7-9632-af6e2323e908">

**Comment by dickhfchan** [comment]
Hi @longxiaofei , it works.
