### ISSUE TITLE
TypeError: Object of type Period is not JSON serializable

### ISSUE THREAD

**Issue by eddyojb88** [Kanaries/pygwalker#63]
Analyzing data by period is useful for analyzing data by e.g. quarter, which is common in financial objectives.  I think that a potential solution to using a 'Period' column type  is to convert to datetime in the backend and warn the user that this has occurred:

`df['period_temp'] = df['period'].astype('datetime64[ns]')`

Ideally, the original values would be stored as a map and assigned as labels in a time series plot but this sounds complex.

Love this package btw, really pleased this is finally here, been looking for incentives to entice excel users out of their bubble for a long time and this might be the boon!

**Comment by Asm-Def** [comment]
@eddyojb88 Hello! there's a PR #99 that tries to fix this, please have a try with `pygwalker>=0.1.7`

**Comment by longxiaofei** [comment]
No feedback for too long, so temporarily closing this issue. If there are any problems, it can be reopened.
