### ISSUE TITLE
Hide chat

### ISSUE THREAD

**Issue by pplonski** [Kanaries/pygwalker#648]
Thank you for amazing package! :1st_place_medal: 

I'm building new ML editor that is based on Python notebooks and would like to use Pygwalker as recipe for exploratory analysis. 

Is there any option to hide the Chat tab in Jupyter? We already have chat feature in our editor and it might be confusing for users.

Thank you!

**Comment by longxiaofei** [comment]
Hi @pplonski 

try to set `show_cloud_tool` as `False`.

`xxxx(dataset, show_cloud_tool=False)`

**Comment by pplonski** [comment]
It is working perfect! Thank you :1st_place_medal:
