### ISSUE TITLE
Force table format and crosstab to excel

### ISSUE THREAD

**Issue by danilo-css** [Kanaries/pygwalker#69]
Thank you so much for this package, I've been looking for something like this for ages. Some features from Tableau I would like to see:

1 - Force table format, as I very much like it for basic data exploration.
2 - Crosstab to excel, to download the data being shown in the viz to Excel, CSV or something.

Also, reinforcing #11, support for streamlit would very much be appreciated and would increase the potential of this package by a lot.

**Comment by ObservedObserver** [comment]
Those features are supported in the latest version of pygwalker.
