### ISSUE TITLE
[Feat] Force data types in code

### ISSUE THREAD

**Issue by jredwards** [Kanaries/pygwalker#70]
When I'm running pygwalker from a jupyter notebook, any time I reload the cell that runs pygwalker, I have to go back in and adjust data types (quantitative, ordinal, etc). For data where pygwalker makes assumptions that I don't want, that means fussing with the data tab any time I reload the data. Would be great to be able to specify those in the .walk call or elsewhere.

**Comment by Asm-Def** [comment]
an argument named `fieldSpecs` has been provided in #96 and pre-released in `pygwalker==0.1.7a3`.
here are some using hints
https://github.com/Kanaries/pygwalker/blob/feat/sup-field-spec-as-args/tests/field-spec.ipynb

**Comment by jredwards** [comment]
This is perfect. Thank you!
