### ISSUE TITLE
Running Pygwalker on Pyodide

### ISSUE THREAD

**Issue by davidgasquez** [Kanaries/pygwalker#81]
You can run PygWalker on Pyodide! The following notebook works on VSCode thanks to the `joyceerhl.vscode-pyodide` extension.

https://github.com/davidgasquez/datalab/blob/main/notebooks/2023-03-14-Pyodide.ipynb

**Comment by westurner** [comment]
- #36
  - JupyterLite is built on pyodide
  - joyceerhl.vscode-pyodide is a pyodide  Jupyter kernel IIRC?
    - [ ] Does pygwalker also work in https://vscode.dev (VScode in WASM in a tab)?

**Comment by westurner** [comment]
vscode.dev URLs [1] for pygwalker demo notebooks:
-
https://vscode.dev/github/davidgasquez/datalab/blob/main/notebooks/2023-03-14-Pyodide.ipynb
-
https://vscode.dev/github/Kanaries/pygwalker/blob/main/examples/jupyter_demo.ipynb

[1]
https://github.com/microsoft/vscode-remote-repositories-github?tab=readme-ov-file#integration-with-vscodedev
