### ISSUE TITLE
Removing automatic update check

### ISSUE THREAD

**Issue by Julius-Plehn** [Kanaries/pygwalker#91]
Hi thanks for the great work with PyWalker!

We are considering to use it in a project but noticed that you added an automatic update check triggered every time the library is imported the first time. Commit: [to:feat:reminder to update ](https://github.com/Kanaries/pygwalker/commit/201e27040121a469a060ec9667a9b2fae9a82890)
Please reconsider if this check is really necessary, as I believe the update mechanism provided by pip is the preferred mechanism for checking for updates.
In addition to this, this is also a privacy issue for some users, so removing this check would help with adoption.

**Comment by ObservedObserver** [comment]
Hi, the auto-update check is developed for the reason that we are updating pygwalker very frequently. And there are going to be lots of essential features that will be published soon. We hope people are using the latest version so it can really help more people. The version updates checker only fetches the latest version and compares it with the local version. No other data is sent.

I understand your concerns, so we will add a global parameter to allow users to disable the auto-update checker if they do not want it. Thanks for your feedback.

**Comment by ObservedObserver** [comment]
Hi, the auto-update check is developed for the reason that we are updating pygwalker very frequently. And there are going to be lots of essential features that will be published soon. We hope people are using the latest version so it can really help more people. The version updates checker only fetches the latest version and compares it with the local version. No other data is sent.

I understand your concerns, so we will add a global parameter to allow users to disable the auto-update checker if they do not want it. Thanks for your feedback.

**Comment by Julius-Plehn** [comment]
Thank you for addressing my concerns!
Do you already know how you are going to implement such change? Do you want to use some global variable for that or as an option to PyGWalker when you are plotting a dataframe?

If you want to notify about updates by default my preference would be to offer an additional extra variant like you do e.g. for streamlit and polars.

**Comment by Asm-Def** [comment]
@Julius-Plehn 
Hello! We're going to provide a user-wide privacy policy configuration method since `pygwalker==0.1.7a0`, please check it out in #95.
