### ISSUE TITLE
Can I put pygwalker into django web application?

### ISSUE THREAD

**Issue by eternal-bug** [Kanaries/pygwalker#94]
Hello!

It is a wonderful module. I am a beginner in django. Is it possible to use this application inside an html div tag?(The file is uploaded through the front end and then processed in the background to return the graphic display and editor to the front end.) Thanks.

**Comment by Asm-Def** [comment]
Yes, please refer to the document of `pyg.to_html` (call `help(pyg.to_html)` in python).

**Comment by eternal-bug** [comment]
Thank you very much! I'll try it.

**Comment by P3RI9** [comment]
> Yes, please refer to the document of `pyg.to_html` (call `help(pyg.to_html)` in python for it).

Hi, I've tried to insert pygwalker into a Django div with mark_safe and file keeps loading forever
